import type {Entity,Snapshot} from '../../lib/engi/types';
import {indexes} from '../../lib/engi/indexes';
import {textValue,trusted,entityTypes} from '../../lib/engi/knowledge/properties';
import {canonicalTargets} from '../../lib/engi/questions/recipe-factory';
import {retention} from '../../lib/engi/engine';
import {KnowledgeImage} from './KnowledgeImage';
import {saveKnowledge} from '../../services/knowledge-service';
export function EntityPage({entity,snapshot,onEdit,onClose,onOpen,onReload}:{entity:Entity;snapshot:Snapshot;onEdit:()=>void;onClose:()=>void;onOpen:(e:Entity)=>void;onReload:()=>void}){
 const b=snapshot.bundle,ix=indexes(b);const facts=ix.factsByEntity.get(entity.id)??[];const incoming=ix.incomingFactsByTarget.get(entity.id)??[];const media=ix.mediaByEntity.get(entity.id)??[];const readyFacts=new Set(canonicalTargets(b).map(i=>i.factId));
 return <div className="overlay"><section className="editor-panel" role="dialog" aria-modal="true" aria-label={entity.name}><div className="section-heading"><h2>{entity.name}</h2><button className="icon-button" onClick={onClose} aria-label="Закрыть">×</button></div>{media[0]&&<KnowledgeImage src={media[0].url} alt={entity.name} className="detail-image"/>}<p className="eyebrow">{entityTypes(b).find(t=>t.id===entity.type)?.name}</p>{entity.aliases.length>0&&<p className="muted">{entity.aliases.join(' · ')}</p>}{entity.summary&&<p>{entity.summary}</p>}<div className="tag-chips">{[...ix.tagsByEntity.get(entity.id)??[]].map(id=><span className="chip" key={id}>{b.tags.find(t=>t.id===id)?.name}</span>)}</div><button className="button primary" onClick={onEdit}>Редактировать · Добавить поле</button><h3>Свойства</h3><div className="detail-facts">{facts.map(f=>{const m=snapshot.memories.find(m=>m.id.startsWith(`fact:${f.id}:`));return <div key={f.id}><span>{ix.propertyById.get(f.key)?.name??f.key}</span>{f.valueEntityId?<button className="text-button" onClick={()=>{const e=ix.entityById.get(f.valueEntityId!);if(e)onOpen(e)}}>{textValue(f,b)}</button>:<strong>{textValue(f,b)}</strong>}<small>{!trusted(f)?'Не участвует в обучении':!readyFacts.has(f.id)?'Для обучения нужны подходящие данные или настройки поля':!m?.firstSuccessAt?'Не изучалось':new Date(m.card.due).getTime()<=Date.now()?'Пора повторить':m.card.stability>=30?'Закреплено 30д+':`Помню ≈ ${Math.round(retention(m)*100)}%`}</small>{f.source.url?<a href={f.source.url} target="_blank" rel="noreferrer">{f.source.name} ↗</a>:<small>{f.source.name}</small>}{f.upstreamConflict&&<p className="bad-text">Пакет содержит другую версию. Сохранена ваша правка.</p>}</div>})}</div><h3>Связанные объекты</h3>{incoming.length?incoming.map(f=><div className="review-row" key={f.id}><span>{ix.propertyById.get(f.key)?.name}</span><button className="text-button" onClick={()=>{const e=ix.entityById.get(f.entityId);if(e)onOpen(e)}}>{ix.entityById.get(f.entityId)?.name}</button></div>):<p className="muted">Пока нет входящих связей.</p>}<h3>Изображения</h3><div className="exemplar-grid">{media.map(m=><div key={m.id}><KnowledgeImage src={m.url} alt={entity.name}/><small>{m.role} · {m.license}</small><button className="text-button" disabled={m.primary} onClick={async()=>{await saveKnowledge({media:media.map(x=>({...x,primary:x.id===m.id}))});onReload()}}>{m.primary?'Основное':'Сделать основным'}</button><label className="check-label"><input type="checkbox" checked={m.learningExemplar!==false} onChange={async e=>{await saveKnowledge({media:[{...m,learningExemplar:e.target.checked}]});onReload()}}/>Для обучения</label></div>)}</div></section></div>
}
