import {useRef,useState} from 'react';
import type {Task} from '../../lib/engi/types';
export function SortChallengeCard({task,initialOrder,feedback,busy,onPersist,onSubmit,onNext}:{task:Task;initialOrder?:string[];feedback:any;busy:boolean;onPersist:(v:string[])=>void;onSubmit:(v:string[])=>void;onNext:()=>void}){
 const [order,setOrder]=useState(initialOrder??task.items.map(i=>i.entityId)),[dragging,setDragging]=useState<string>(),[drop,setDrop]=useState<number>();const drag=useRef<{id:string;to:number;centers:number[]}|null>(null),list=useRef<HTMLDivElement>(null);
 const move=(id:string,to:number)=>{const next=order.filter(x=>x!==id);next.splice(Math.max(0,Math.min(to,next.length)),0,id);setOrder(next);onPersist(next);};
 return <><p className="matching-help">Перетащите события: самое раннее сверху, самое позднее снизу.</p><div ref={list} className="feed-sort" aria-label="Порядок событий">{order.map((id,n)=><div className={`sort-row ${dragging===id?'is-dragging':''} ${drop===n?'is-drop-target':''}`} data-item={id} key={id} onPointerDown={e=>{if(busy||feedback||(e.target as HTMLElement).closest('button'))return;drag.current={id,to:n,centers:[...list.current!.querySelectorAll('[data-item]')].map(row=>{const box=row.getBoundingClientRect();return box.top+box.height/2;})};setDragging(id);e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{const g=drag.current;if(g?.id!==id)return;const insertion=g.centers.findIndex(y=>e.clientY<y),to=insertion<0?order.length-1:Math.max(0,insertion-(order.indexOf(id)<insertion?1:0));g.to=to;setDrop(to);}} onPointerUp={e=>{const g=drag.current;drag.current=null;setDragging(undefined);setDrop(undefined);try{e.currentTarget.releasePointerCapture(e.pointerId)}catch{}if(g?.id===id)move(id,g.to);}} onPointerCancel={()=>{drag.current=null;setDragging(undefined);setDrop(undefined)}}><span>⠿ {task.items.find(i=>i.entityId===id)?.name}{task.contextual?.supportTargetIds.includes(task.items.find(i=>i.entityId===id)!.targetId)&&<small> · ориентир</small>}</span><div><button disabled={busy||!!feedback||n===0} aria-label={`Выше: ${task.items.find(i=>i.entityId===id)?.name}`} onClick={()=>move(id,n-1)}>↑</button><button disabled={busy||!!feedback||n===order.length-1} aria-label={`Ниже: ${task.items.find(i=>i.entityId===id)?.name}`} onClick={()=>move(id,n+1)}>↓</button></div></div>)}</div>
 {!feedback?<button className="button primary" disabled={busy} onClick={()=>onSubmit(order)}>Проверить порядок</button>:<div className="sort-result" role="status"><strong>{feedback.score===1?'Верный порядок ✓':'Посмотрите на последовательность'}</strong>{feedback.score!==1&&<ol>{[...task.items].sort((a,b)=>a.year!-b.year!).map(i=><li key={i.entityId}>{i.name} · {i.year}</li>)}</ol>}{feedback.score!==1&&<button className="button outline" disabled={busy} onClick={onNext}>Далее →</button>}</div>}
 </>;
}
