import {useRef,useState} from 'react';
import type {Task} from '../../lib/engi/types';
export function SortChallengeCard({task,initialOrder,feedback,busy,onPersist,onSubmit,onNext}:{task:Task;initialOrder?:string[];feedback:any;busy:boolean;onPersist:(v:string[])=>void;onSubmit:(v:string[])=>void;onNext:()=>void}){
 const [order,setOrder]=useState(initialOrder??task.items.map(i=>i.entityId));const drag=useRef<string|null>(null),list=useRef<HTMLDivElement>(null);
 const move=(id:string,to:number)=>setOrder(old=>{const next=old.filter(x=>x!==id);next.splice(Math.max(0,Math.min(to,next.length)),0,id);onPersist(next);return next});
 return <><div ref={list} className="feed-sort">{order.map((id,n)=><div className="sort-row" data-item={id} key={id} onPointerDown={e=>{if(busy||feedback||(e.target as HTMLElement).closest('button'))return;drag.current=id;e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(drag.current!==id)return;const rows=[...list.current?.querySelectorAll('[data-item]')??[]],to=rows.findIndex(row=>e.clientY<row.getBoundingClientRect().top+row.getBoundingClientRect().height/2);move(id,to===-1?order.length-1:to)}} onPointerUp={()=>{drag.current=null}} onPointerCancel={()=>{drag.current=null}}><span>⠿ {task.items.find(i=>i.entityId===id)?.name}</span><div><button disabled={busy||!!feedback||n===0} aria-label={`Выше: ${task.items.find(i=>i.entityId===id)?.name}`} onClick={()=>move(id,n-1)}>↑</button><button disabled={busy||!!feedback||n===order.length-1} aria-label={`Ниже: ${task.items.find(i=>i.entityId===id)?.name}`} onClick={()=>move(id,n+1)}>↓</button></div></div>)}</div>
 {!feedback?<button className="button primary" disabled={busy} onClick={()=>onSubmit(order)}>Проверить порядок</button>:<div className="sort-result" role="status"><strong>{feedback.score===1?'Верный порядок ✓':'Посмотрите на последовательность'}</strong>{feedback.score!==1&&<ol>{[...task.items].sort((a,b)=>a.year!-b.year!).map(i=><li key={i.entityId}>{i.name} · {i.year}</li>)}</ol>}{feedback.score!==1&&<button className="button outline" disabled={busy} onClick={onNext}>Далее →</button>}</div>}
 </>;
}
