import {useEffect,useRef,useState} from 'react';
import type {SessionRow} from '../../db/engi-db';
import type {Task} from '../../lib/engi/types';
import {trainerService} from '../../services/trainer-service';
import {assess} from '../../lib/engi/engine';
import {KnowledgeImage} from '../knowledge/KnowledgeImage';
import {mediaStore} from '../../media/media-store';
const reasonLabel:Record<string,string>={due:'Пора повторить',new:'Новое знание',weak:'Закрепляем',confusion:'Различаем похожее',retry:'После ошибки',challenge:'Небольшой вызов'};
export function FeedViewport({children}:{children:React.ReactNode}){return <div className="feed-viewport">{children}</div>}
export function FeedbackLayer({task,feedback,onNext,busy=false}:{task:Task;feedback:any;onNext:()=>void;busy?:boolean}){const correct=feedback.score===1;const fmt=task.recipe.format;const expected=['sort','missing'].includes(fmt)?[...task.items].sort((a,c)=>a.year!-c.year!).map(i=>i.name).join(' → '):task.items.map(i=>`${i.answer}${fmt==='timeline'?' год':''}`).join(' · ');return <div className={`feed-feedback ${correct?'is-correct':'is-wrong'}`} role="status"><strong>{correct?'✓ Верно':'× Верный ответ'}</strong>{!correct&&<>{feedback.chosen!==undefined&&typeof feedback.chosen==='string'&&<small>Вы выбрали: {task.options.find(o=>o.id===feedback.chosen)?.name??feedback.chosen}</small>}<p>{expected}</p>{task.items[0].summary&&<small>{task.items[0].summary}</small>}<button className="button primary" disabled={busy} onClick={onNext}>Продолжить</button><small>Или смахните вверх</small></>}</div>}
function SortChallengeCard({task,onSubmit,locked}:{task:Task;onSubmit:(v:string[])=>void;locked:boolean}){const [order,setOrder]=useState(task.items.map(i=>i.entityId));const drag=useRef<string|null>(null);const list=useRef<HTMLDivElement>(null);const move=(id:string,to:number)=>setOrder(old=>{const next=old.filter(x=>x!==id);next.splice(Math.max(0,Math.min(to,next.length)),0,id);return next});return <><div ref={list} className="feed-sort">{order.map((id,n)=><div className="sort-row" data-item={id} key={id} onPointerDown={e=>{if(locked||(e.target as HTMLElement).closest('button'))return;drag.current=id;e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(drag.current!==id)return;const rows=[...list.current?.querySelectorAll('[data-item]')??[]];const to=rows.findIndex(row=>{const rect=row.getBoundingClientRect();return e.clientY<rect.top+rect.height/2});move(id,to===-1?order.length-1:to)}} onPointerUp={()=>{drag.current=null}} onPointerCancel={()=>{drag.current=null}}><span>≡ {task.items.find(i=>i.entityId===id)?.name}</span><div><button disabled={locked||n===0} aria-label="Выше" onClick={()=>move(id,n-1)}>↑</button><button disabled={locked||n===order.length-1} aria-label="Ниже" onClick={()=>move(id,n+1)}>↓</button></div></div>)}</div><button className="button primary" disabled={locked} onClick={()=>onSubmit(order)}>Проверить порядок</button></>}
function TimelineCard({task,onSubmit,locked}:{task:Task;onSubmit:(v:any)=>void;locked:boolean}){const i=task.items[0],min=Math.floor((i.year!-60)/10)*10,max=Math.ceil((i.year!+60)/10)*10;const [value,setValue]=useState(Math.round((min+max)/2));const valueRef=useRef(value);return <div className="feed-timeline"><output>{value}</output><input type="range" aria-label="Примерный год" min={min} max={max} step={1} value={value} disabled={locked} onChange={e=>{const v=Number(e.target.value);setValue(v);valueRef.current=v}} onPointerUp={()=>{if(!locked)onSubmit({[i.entityId]:valueRef.current})}} onKeyUp={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)&&!locked)onSubmit({[i.entityId]:valueRef.current})}}/><div><span>{min}</span><span>{max}</span></div><small>Перетащите и отпустите · приблизительная оценка</small></div>}
function QuestionCard({task,feedback,locked,onSubmit,onImageFail}:{task:Task;feedback:any;locked:boolean;onSubmit:(v:any)=>void;onImageFail:()=>void}){const [revealed,setRevealed]=useState(false);const item=task.items[0],fmt=task.recipe.format;let prompt=task.recipe.label??'Выберите ответ';if(fmt==='timeline')prompt='Примерно когда?';if(fmt==='sort')prompt=task.items[0].year&&task.recipe.answerKey!=='identity'?'Расположите по возрастанию':'Расположите по порядку';if(fmt==='missing')prompt='Кто пропущен в этой последовательности?';const recall=fmt==='recall_reveal'||fmt==='recall';return <div className="feed-question"><div className="feed-cue">{fmt==='missing'?<ol className="feed-sequence">{task.sequence?.map((i,n)=><li key={n}>{i?.name??'?'}</li>)}</ol>:fmt==='sort'?<span className="challenge-mark">↕</span>:task.recipe.cue==='image'&&item.image?<KnowledgeImage src={item.image} alt="Объект для узнавания" onFail={onImageFail}/>:<h1>{item.name}</h1>}</div><div className="feed-actions"><h2>{prompt}</h2>{recall?<>{!revealed&&!feedback?<><button className="feed-option primary-action" disabled={locked} onClick={()=>setRevealed(true)}>Открыть ответ</button><p className="muted">Сначала вспомните мысленно</p></>:<><h3 className="revealed-answer">{item.answer}</h3><p className="muted">Получилось вспомнить?</p><div className="recall-decisions"><button className="feed-option" disabled={locked} onClick={()=>onSubmit(false)}>Не вспомнил</button><button className="feed-option" disabled={locked} onClick={()=>onSubmit(true)}>Вспомнил</button></div></>}</>:fmt==='sort'?<SortChallengeCard task={task} locked={locked} onSubmit={onSubmit}/>:fmt==='timeline'?<TimelineCard task={task} locked={locked} onSubmit={onSubmit}/>:<div className="feed-options">{task.options.filter(o=>!feedback||feedback.score===1||o.id===feedback.chosen||o.id===item.answerId||fmt==='missing').map(o=>{const right=feedback&&(['missing'].includes(fmt)?o.id===[...task.items].sort((a,c)=>a.year!-c.year!)[1]?.entityId:o.id===item.answerId);return <button className={`feed-option ${right?'answer-correct':feedback?.chosen===o.id?'answer-wrong':''}`} disabled={locked} key={o.id} onClick={()=>onSubmit(o.id)}>{o.name}{right?' ✓':feedback?.chosen===o.id?' ×':''}</button>})}</div>}</div></div>}
export function StudyFeed({initial,onExit}:{initial:SessionRow;onExit:()=>void}){
 const [session,setSession]=useState(initial),[feedback,setFeedback]=useState<any>(null),[state,setState]=useState<'idle'|'locked'|'feedback'|'exiting'>('idle'),[error,setError]=useState(''),[imageFailed,setImageFailed]=useState(false),[report,setReport]=useState(false),[reportText,setReportText]=useState('');const task=session.tasks[session.currentPosition];const lock=useRef(false),advancing=useRef(false),alive=useRef(true),started=useRef(Date.now()),touch=useRef<number|null>(null),timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);const sessionRef=useRef(session);sessionRef.current=session;
 useEffect(()=>()=>{alive.current=false;clearTimeout(timer.current)},[]);
 useEffect(()=>{lock.current=false;advancing.current=false;setState('idle');setFeedback(null);setError('');setImageFailed(false);started.current=Date.now();let valid=true;if(task)trainerService.getFeedback(task.id).then(f=>{if(f&&valid){lock.current=true;setState('feedback');setFeedback(f);if(f.score===1)timer.current=setTimeout(()=>advance(),280)}}).catch(e=>setError(e.message));const next=session.tasks.slice(session.currentPosition,session.currentPosition+4);mediaStore.prewarm(next.flatMap(t=>t.items.map(i=>i.image).filter((v):v is string=>!!v)));return()=>{valid=false;clearTimeout(timer.current)}},[task?.id]);
 async function advance(skip=false){if(advancing.current)return;advancing.current=true;clearTimeout(timer.current);setState('exiting');try{const s=await trainerService.advanceFeed(sessionRef.current.id,skip);if(!alive.current)return;setSession(s);if(!s.tasks[s.currentPosition]){setState('idle');setError('Сейчас нет новых подходящих вопросов. Можно выйти и вернуться позже.')}}catch(e){setError((e as Error).message);setState('feedback')}finally{advancing.current=false}}
 async function submit(value:any){if(lock.current||!task||imageFailed)return;lock.current=true;setState('locked');const assessment=assess(task,value);setFeedback({...assessment,items:task.items,chosen:value});const start=performance.now();try{const result=await trainerService.answer({sessionId:session.id,taskId:task.id,answer:value,latencyMs:Date.now()-started.current});if(!alive.current)return;setFeedback(result.feedback);setState('feedback');if(result.feedback.score===1)timer.current=setTimeout(()=>advance(),Math.max(0,280-(performance.now()-start)));if('vibrate' in navigator)navigator.vibrate?.(result.feedback.score===1?10:[20,30,20])}catch(e){setFeedback(null);setError((e as Error).message);setState('idle');lock.current=false}}
 const today=session.completedCount??0;return <main className={`study-feed state-${state}`}><header className="feed-header"><button className="icon-button" aria-label="Выйти из обучения" disabled={state==='locked'||state==='exiting'} onClick={onExit}>×</button><span>{reasonLabel[task?.reason]??'Практика'}</span><span>{today} ответов</span><button className="icon-button" aria-label="Сообщить об ошибке" onClick={()=>setReport(true)}>⋯</button></header><FeedViewport><div className="feed-current" key={task?.id} onPointerDown={e=>{if(!(e.target as HTMLElement).closest('button,input'))touch.current=e.clientY}} onPointerUp={e=>{if(touch.current!==null&&touch.current-e.clientY>65&&feedback?.score<1&&!['locked','exiting'].includes(state))advance();touch.current=null}}>{task&&<QuestionCard task={task} feedback={feedback} locked={lock.current||state!=='idle'} onSubmit={submit} onImageFail={()=>setImageFailed(true)}/>} {feedback&&task&&<FeedbackLayer task={task} feedback={feedback} busy={state==='locked'||state==='exiting'} onNext={()=>advance()}/>} {error&&<p className="feed-error" role="alert">{error}</p>}{imageFailed&&!feedback&&<div className="feed-error"><p>Изображение не загрузилось. Ответ не будет учтён.</p><button className="button outline" onClick={()=>advance(true)}>Пропустить</button></div>}</div></FeedViewport>{today>0&&today%15===0&&<div className="feed-nudge">✓ {today} ответов сохранено. Можно закончить или продолжить.</div>}<footer className="feed-footer">{task?.recipe.diagnostic?'Проверяем связи · интервалы памяти не меняются':task?.reason==='retry'?'Короткое закрепление после ошибки':'Маленькая практика, долгая память.'}</footer>{report&&<div className="overlay"><section className="editor-panel"><h2>Ошибка в вопросе</h2><textarea value={reportText} onChange={e=>setReportText(e.target.value)} placeholder="Что нужно проверить?"/><button className="button primary" onClick={async()=>{await trainerService.reportQuestion(task.id,reportText);setReport(false);setReportText('')}}>Сохранить</button><button className="button outline" onClick={()=>setReport(false)}>Закрыть</button></section></div>}</main>
}
