import {indexes} from './indexes';
import { fsrs,createEmptyCard,Rating,type Card } from 'ts-fsrs';
import type { Bundle,Memory,Recipe,Task,Item,Format } from './types';
export const scheduler=fsrs({request_retention:0.9,enable_fuzz:false});
export const FACT_TYPES:Record<string,{valueKind:string;subject:string[];target?:string[]}>={created_by:{valueKind:'entity',subject:['artwork'],target:['person']},creation_date:{valueKind:'date',subject:['artwork']},presidency_start:{valueKind:'date',subject:['person']},presidency_end:{valueKind:'date',subject:['person']},party:{valueKind:'entity',subject:['person'],target:['organization']},movement:{valueKind:'entity',subject:['person','artwork'],target:['movement']},birth_date:{valueKind:'date',subject:['person']},invented_by:{valueKind:'entity',subject:['invention'],target:['person']},event_start:{valueKind:'date',subject:['event']},capital:{valueKind:'entity',subject:['country'],target:['city']},definition:{valueKind:'text',subject:['concept','invention']}};
export function shuffle<T>(a:T[]):T[]{return [...a].sort(()=>Math.random()-.5)}
export function normalize(s:string){return s.toLowerCase().replace(/ё/g,'е').replace(/[^\p{L}\p{N}]/gu,'')}
export function hydrate(m:Memory):Card{return {...m.card,due:new Date(m.card.due),last_review:m.card.last_review?new Date(m.card.last_review):undefined}}
export function retention(m:Memory){return m.firstSuccessAt?scheduler.get_retrievability(hydrate(m),new Date(),false):0}
export function recipes(b:Bundle):Recipe[]{
 const result:Recipe[]=[];const ix=indexes(b);
 for(const tag of b.tags){const members=ix.entitiesByTag.get(tag.id)??[];const types=[...new Set(members.map(e=>e!.type))];
 for(const type of types){const facts=members.filter(e=>e.type===type).flatMap(e=>ix.factsByEntity.get(e.id)??[]);const keys=[...new Set(facts.map(f=>f.key))];
 if(members.some(e=>ix.mediaByEntity.has(e.id))){for(const format of ['choice','recall','match'] as Format[])result.push({id:`${tag.id}:identity:${format}`,format,tag:tag.id,subjectType:type,cue:'image',answerKey:'identity',memoryKey:'image_to_name',diagnostic:false});}
 for(const key of keys){const def=FACT_TYPES[key];if(!def)continue;const date=def.valueKind==='date';for(const format of (date?['choice','recall','sort','timeline','missing']:['choice','recall','match','categorize']) as Format[]){result.push({id:`${tag.id}:${key}:${format}`,format,tag:tag.id,subjectType:type,cue:date?'name':(members.some(e=>ix.mediaByEntity.has(e.id))?'image':'name'),answerKey:key,memoryKey:date?`${key}_to_year`:`${members.some(e=>ix.mediaByEntity.has(e.id))?'image':'name'}_to_${key}`,diagnostic:['sort','timeline','missing'].includes(format)});}}
 }}return result;
}
export function eligible(b:Bundle,r:Recipe):Item[]{const ix=indexes(b);return (r.tag?ix.entitiesByTag.get(r.tag)??[]:b.entities).filter(e=>!r.subjectType||e.type===r.subjectType).flatMap(e=>{
 const image=ix.mediaByEntity.get(e.id)?.[0]?.url;if(r.cue==='image'&&!image)return [];
 if(r.answerKey==='identity')return [{entityId:e.id,name:e.name,image,targetId:`entity:${e.id}:image_to_name`,answer:e.name,aliases:e.aliases,answerId:e.id,sourceUrl:ix.mediaByEntity.get(e.id)?.[0]?.sourceUrl||''}];
 const all=ix.factsByEntityAndKey.get(e.id)?.get(r.answerKey)??[];if(all.some(f=>!['direct','verified'].includes(f.verification)))return [];const values=all.filter(f=>['direct','verified'].includes(f.verification));if(values.length!==1)return [];const f=values[0];const obj=ix.entityById.get(f.valueEntityId??'');const year=f.dateStart?Number(f.dateStart.slice(0,4)):undefined;if(f.valueKind==='date'&&(!['year','day','month'].includes(f.datePrecision||'')||!Number.isFinite(year)))return [];
 const answer=obj?.name??f.valueText??String(f.valueNumber??year??'');if(!answer)return [];
 return [{entityId:e.id,name:e.name,image,targetId:`fact:${f.id}:${r.memoryKey}`,answer,aliases:obj?.aliases??[],answerId:obj?.id??answer,year,sourceUrl:f.source.url}];});}
export function preflight(t:Task){const a=t.items;if(!a.length)return false;if(t.recipe.format==='match'&&(a.length<3||new Set(a.map(i=>i.answerId)).size!==a.length))return false;if(['sort','timeline','missing'].includes(t.recipe.format)&& (a.length<3||new Set(a.map(i=>i.year)).size!==a.length))return false;if(['sort','timeline','missing'].includes(t.recipe.format)){const sorted=[...a].sort((x,y)=>x.year!-y.year!);for(let i=1;i<sorted.length;i++)if(sorted[i-1].year!>=sorted[i].year!)return false;}if(t.recipe.format==='categorize'&&new Set(a.map(i=>i.answerId)).size<2)return false;if(t.recipe.format==='choice'&&(t.options.length<3||t.options.filter(o=>o.id===a[0].answerId).length!==1))return false;return new Set(t.options.map(o=>normalize(o.name))).size===t.options.length;}
export function generateSession(b:Bundle,mem:Memory[],tag='all',format='mixed',mode='daily'):Task[]{
 const memoryById=new Map(mem.map(m=>[m.id,m]));const pools=new Map<string,Item[]>();const getPool=(r:Recipe)=>{let p=pools.get(r.id);if(!p){p=eligible(b,r);pools.set(r.id,p)}return p};
 const rs=recipes(b).filter(r=>(tag==='all'||r.tag===tag)&&(format==='mixed'||r.format===format));const out:Task[]=[];let recent:string[]=[];
 for(let n=0;n<15;n++){const candidates=shuffle(rs).filter(r=>!out.length||out[out.length-1].recipe.format!==r.format||format!=='mixed');let built:Task|undefined;
 for(const r of candidates){let pool=shuffle(getPool(r)).filter(i=>!recent.includes(i.entityId));if(pool.length<1)pool=shuffle(getPool(r));pool.sort((a,c)=>{const weight=(i:Item)=>{const m=memoryById.get(i.targetId);if(mode==='weak')return m?(m.attempts-m.correct)*10:0;if(mode==='explore')return m?0:10;return m?(new Date(m.card.due)<=new Date()?30:0)+(m.attempts-m.correct)*2:8;};return weight(c)-weight(a)});if(!pool.length)continue;
 let items=pool.slice(0,['choice','recall'].includes(r.format)?1:4);if(r.format==='match'){const seen=new Set<string>();items=pool.filter(i=>{if(seen.has(i.answerId))return false;seen.add(i.answerId);return true}).slice(0,4);}if(['sort','timeline','missing'].includes(r.format)){const seen=new Set<number>();items=pool.filter(i=>{if(seen.has(i.year!))return false;seen.add(i.year!);return true}).slice(0,4);}
 const all=getPool(r);const unique=Array.from(new Map(all.map(i=>[i.answerId,{id:i.answerId,name:i.answer}])).values());let options=unique;
 if(r.format==='choice'){const m=memoryById.get(items[0].targetId);const wrong=shuffle(unique.filter(o=>o.id!==items[0].answerId));wrong.sort((a,c)=>(m?.confusions[c.id]||0)-(m?.confusions[a.id]||0));options=shuffle([{id:items[0].answerId,name:items[0].answer},...wrong.slice(0,3)]);}
 if(['match','categorize'].includes(r.format))options=shuffle(Array.from(new Map(items.map(i=>[i.answerId,{id:i.answerId,name:i.answer}])).values()));
 const m=memoryById.get(items[0].targetId);const t={id:crypto.randomUUID(),recipe:r,items:shuffle(items),options,reason:r.diagnostic?'Проверяем связи':!m?'Новое знание':new Date(m.card.due)<=new Date()?'Пора повторить':'Закрепляем'};if(preflight(t)){built=t;break;}}
 if(!built)break;out.push(built);recent=[...recent,...built.items.map(i=>i.entityId)].slice(-3);
 }return out;
}
export function assess(t:Task,answer:any){const fmt=t.recipe.format;const evidence:{item:Item;correct:boolean;chosen?:string;level:string}[]=[];
 if(fmt==='timeline'){if(!answer||typeof answer!=='object')throw Error('Укажите годы');const scores=t.items.map(i=>Math.abs(Number(answer[i.entityId])-i.year!)<=15?1:0);return {score:scores.reduce<number>((a,b)=>a+b,0)/scores.length,evidence:[],expected:t.items.map(i=>({id:i.entityId,answer:i.answer,year:i.year}))};}
 if(['sort','missing'].includes(fmt)){const expected=[...t.items].sort((a,b)=>a.year!-b.year!).map(i=>i.entityId);if(fmt==='missing'){const target=expected[1];return {score:answer===target?1:0,evidence:[],expected};}if(!Array.isArray(answer)||new Set(answer).size!==t.items.length||!expected.every(x=>answer.includes(x)))throw Error('Заполните все позиции');let correct=0,total=0;for(let i=0;i<answer.length;i++)for(let j=i+1;j<answer.length;j++){total++;if(expected.indexOf(answer[i])<expected.indexOf(answer[j]))correct++;}return {score:correct/total,evidence:[],expected};}
 for(let index=0;index<t.items.length;index++){const item=t.items[index];const val=['match','categorize'].includes(fmt)?answer?.[item.entityId]:answer;const ok=fmt==='recall'?[item.answer,...item.aliases].some(a=>normalize(a)===normalize(String(val??''))):val===item.answerId;evidence.push({item,correct:ok,chosen:String(val??''),level:fmt==='match'?'partial':'direct'});}return {score:evidence.filter(e=>e.correct).length/evidence.length,evidence,expected:t.items.map(i=>({id:i.entityId,answer:i.answer,year:i.year}))};
}
export function updateMemory(old:Memory|undefined,item:Item,correct:boolean,chosen:string|undefined,confidence='medium',fmt:Format='choice'){const now=new Date();const m=old??{id:item.targetId,card:createEmptyCard(now),attempts:0,correct:0,confusions:{}};const pretest=!old&&!correct;if(pretest)return undefined;const rating=!correct?Rating.Again:confidence==='low'?Rating.Hard:fmt==='recall'&&confidence==='high'?Rating.Easy:Rating.Good;const next=scheduler.next(old?hydrate(old):createEmptyCard(now),now,rating).card;return {...m,card:next,attempts:m.attempts+1,correct:m.correct+Number(correct),firstSuccessAt:m.firstSuccessAt??(correct?now.toISOString():undefined),confusions:!correct&&chosen?{...m.confusions,[chosen]:(m.confusions[chosen]||0)+1}:m.confusions};}
