import {z} from 'zod';
import {FACT_TYPES} from './engine.ts';
import type {Bundle} from './types';
const url=z.string().url().refine(s=>s.startsWith('https://'),'Нужна HTTPS-ссылка');
const mediaUrl=z.string().refine(s=>/^engi-media:\/\/[a-f0-9]{64}$/.test(s)||/^media\/[A-Za-z0-9._/-]+$/.test(s),'Нужно локальное изображение');
const entity=z.object({id:z.string().min(1).max(150),type:z.string().min(1),name:z.string().min(1).max(200),aliases:z.array(z.string()).default([]),externalIds:z.record(z.string()).default({})});
const fact=z.object({id:z.string().min(1),entityId:z.string(),key:z.string(),valueKind:z.enum(['entity','text','number','date']),valueEntityId:z.string().optional(),valueText:z.string().optional(),valueNumber:z.number().finite().optional(),dateStart:z.string().optional(),dateEnd:z.string().optional(),datePrecision:z.enum(['year','day','month','circa','range']).optional(),source:z.object({url,name:z.string().min(1),locator:z.string().optional(),family:z.string().optional()}),verification:z.enum(['direct','verified','unverified','ambiguous','conflict','rejected'])});
function validDate(s:string|undefined){if(!s||!/^\d{4}-\d{2}-\d{2}$/.test(s))return false;const d=new Date(s+'T00:00:00Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===s}
const schema=z.object({entities:z.array(entity).max(50000),facts:z.array(fact).max(200000),media:z.array(z.object({id:z.string(),entityId:z.string(),role:z.string(),url:mediaUrl,sourceUrl:url,license:z.string().min(1)})).max(50000),tags:z.array(z.object({id:z.string(),name:z.string(),parentId:z.string().optional()})).max(5000).default([]),entityTags:z.array(z.object({entityId:z.string(),tagId:z.string()})).max(200000).default([]),missing:z.array(z.unknown()).default([]),unresolved:z.array(z.unknown()).default([])});
export function validateImport(input:unknown,existing:Bundle,allowUpdate=false):Bundle{
 const b=schema.parse(input) as Bundle;const e=new Map([...existing.entities,...b.entities].map(e=>[e.id,e]));const tags=new Set([...existing.tags,...b.tags].map(t=>t.id));
 for(const name of ['entities','facts','media','tags'] as const)if(new Set(b[name].map(x=>x.id)).size!==b[name].length)throw Error(`Повторяющийся ID в ${name}`);
 for(const en of b.entities){const old=existing.entities.find(x=>x.id===en.id);if(old&&old.type!==en.type)throw Error('ID уже принадлежит объекту другого типа');for(const [key,value]of Object.entries(en.externalIds)){const duplicate=[...existing.entities,...b.entities].find(x=>x.id!==en.id&&x.externalIds[key]===value);if(duplicate)throw Error(`Объект уже существует: ${duplicate.name} (${duplicate.id}). Используйте его ID.`);}}
 for(const f of b.facts){const def=FACT_TYPES[f.key];if(!def||def.valueKind!==f.valueKind||!def.subject.includes(e.get(f.entityId)?.type||''))throw Error(`Недопустимый факт ${f.id}`);if(f.valueKind==='entity'&&(!e.has(f.valueEntityId||'')||(def.target&&!def.target.includes(e.get(f.valueEntityId!)!.type))))throw Error('Не найден объект ответа или неверный тип');if(!e.has(f.entityId))throw Error('Не найден объект факта');if(f.valueKind==='date'&&(!validDate(f.dateStart)||!validDate(f.dateEnd)||f.dateStart!>f.dateEnd!||!f.datePrecision))throw Error('Неверная дата');if(f.valueKind==='text'&&!f.valueText)throw Error('Пустое значение');if(f.valueKind==='number'&&f.valueNumber===undefined)throw Error('Нет числа');const old=existing.facts.find(x=>x.id===f.id);if(old&&(old.entityId!==f.entityId||old.key!==f.key||old.valueKind!==f.valueKind))throw Error('Released fact ID нельзя переназначать другому знанию');if(old&&!allowUpdate&&JSON.stringify(old)!==JSON.stringify(f))throw Error('Факт с этим ID уже существует. Для исправления используйте редактор.');}
 for(const t of b.tags)if(t.parentId&&!tags.has(t.parentId))throw Error('Неизвестная родительская категория');for(const m of b.media)if(!e.has(m.entityId))throw Error('Изображение без объекта');for(const t of b.entityTags)if(!e.has(t.entityId)||!tags.has(t.tagId))throw Error('Неизвестная подборка или объект');return b;
}
