import {z} from 'zod';
import {properties,entityTypes} from './knowledge/properties';
import type {Bundle} from './types';
const id=z.string().min(1).max(150);
const url=z.string().url().refine(s=>s.startsWith('https://'),'Нужна HTTPS-ссылка');
const origin={origin:z.enum(['pack','user']).optional(),originPackId:id.optional(),originPackVersion:z.number().int().positive().optional(),userModified:z.boolean().optional(),archived:z.boolean().optional(),upstreamConflict:z.boolean().optional(),upstreamValue:z.unknown().optional(),upstreamAcknowledged:z.string().optional()};
const kind=z.enum(['entity','text','number','date','boolean']);
const flag=z.enum(['auto','on','off']);
export const propertySchema=z.object({...origin,id,name:z.string().min(1).max(200),shortName:z.string().optional(),description:z.string().optional(),valueKind:kind,subjectTypes:z.array(id).optional(),targetTypes:z.array(id).optional(),cardinality:z.enum(['one','many']),learnable:z.boolean(),inverse:z.object({enabled:z.boolean(),name:z.string().optional()}).optional(),learning:z.object({forward:z.boolean().optional(),reverse:z.boolean().optional(),choice:flag.optional(),recallReveal:flag.optional(),match:flag.optional(),categorize:flag.optional(),timeline:flag.optional(),sort:flag.optional(),missing:flag.optional()}).optional(),builtIn:z.boolean().optional(),createdAt:z.string().optional(),updatedAt:z.string().optional()});
export const typeSchema=z.object({...origin,id,name:z.string().min(1).max(200),pluralName:z.string().optional(),icon:z.string().optional(),builtIn:z.boolean().optional()});
const entity=z.object({...origin,id,type:id,name:z.string().min(1).max(200),aliases:z.array(z.string()).default([]),externalIds:z.record(z.string()).default({}),summary:z.string().max(400).optional()});
const source=z.object({kind:z.enum(['url','pack','manual']).optional(),url:url.optional(),name:z.string().min(1),locator:z.string().optional(),family:z.string().optional()}).refine(s=>s.kind==='manual'||!!s.url,'Добавьте HTTPS-источник или отметьте личное знание');
const fact=z.object({...origin,id,entityId:id,key:id,valueKind:kind,valueEntityId:id.optional(),valueText:z.string().optional(),valueNumber:z.number().finite().optional(),valueBoolean:z.boolean().optional(),dateStart:z.string().optional(),dateEnd:z.string().optional(),datePrecision:z.enum(['year','day','month','circa','range']).optional(),source,verification:z.enum(['user_confirmed','direct','verified','unverified','ambiguous','conflict','rejected'])});
export const validDate=(s:string|undefined)=>{if(!s||!/^\d{4}-\d{2}-\d{2}$/.test(s))return false;const d=new Date(s+'T00:00:00Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===s};
const schema=z.object({entities:z.array(entity).max(50000),facts:z.array(fact).max(200000),media:z.array(z.object({...origin,id,entityId:id,role:z.string(),url:z.string().refine(s=>/^engi-media:\/\/[a-f0-9]{64}$/.test(s)||/^media\/[A-Za-z0-9._/-]+$/.test(s),'Нужно локальное изображение'),sourceUrl:url.optional(),license:z.string().min(1),primary:z.boolean().optional(),learningExemplar:z.boolean().optional()})).max(50000),properties:z.array(propertySchema).max(5000).default([]),entityTypes:z.array(typeSchema).max(5000).default([]),tags:z.array(z.object({...origin,id,name:z.string().min(1),parentId:id.optional()})).max(5000).default([]),entityTags:z.array(z.object({...origin,entityId:id,tagId:id})).max(200000).default([]),missing:z.array(z.unknown()).default([]),unresolved:z.array(z.unknown()).default([])});
export function validateImport(input:unknown,existing:Bundle,allowUpdate=false):Bundle{
 const b=schema.parse(input) as Bundle;const e=new Map([...existing.entities,...b.entities].map(e=>[e.id,e]));const tagMap=new Map([...existing.tags,...b.tags].map(t=>[t.id,t]));const defs=new Map(properties({...existing,properties:[...existing.properties??[],...b.properties??[]]}).map(p=>[p.id,p]));const types=new Set(entityTypes({...existing,entityTypes:[...existing.entityTypes??[],...b.entityTypes??[]]}).map(p=>p.id));
 for(const name of ['entities','facts','media','tags','properties','entityTypes'] as const){const rows=b[name]??[];if(new Set(rows.map(x=>x.id)).size!==rows.length)throw Error(`Повторяющийся ID в ${name}`)}
 const assignments=b.entityTags.map(t=>JSON.stringify([t.entityId,t.tagId]));if(new Set(assignments).size!==assignments.length)throw Error('Повтор тега объекта');
 for(const p of b.properties??[]){const old=properties(existing).find(x=>x.id===p.id);if(old&&old.valueKind!==p.valueKind)throw Error('Тип существующего поля нельзя менять');for(const t of [...p.subjectTypes??[],...p.targetTypes??[]])if(!types.has(t))throw Error('Неизвестный тип поля')}
 for(const en of b.entities){if(!types.has(en.type))throw Error('Неизвестный тип объекта');for(const [key,value]of Object.entries(en.externalIds)){const duplicate=[...e.values()].find(x=>x.id!==en.id&&x.externalIds[key]===value);if(duplicate)throw Error(`Объект уже существует: ${duplicate.name}`)}}
 for(const f of b.facts){const def=defs.get(f.key);if(!def||def.valueKind!==f.valueKind||!e.has(f.entityId)||(def.subjectTypes?.length&&!def.subjectTypes.includes(e.get(f.entityId)!.type)))throw Error(`Недопустимый факт ${f.id}`);if(f.valueKind==='entity'&&(!e.has(f.valueEntityId||'')||(def.targetTypes?.length&&!def.targetTypes.includes(e.get(f.valueEntityId!)!.type))))throw Error('Не найден объект ответа или неверный тип');if(f.valueKind==='date'&&(!validDate(f.dateStart)||!validDate(f.dateEnd)||f.dateStart!>f.dateEnd!||!f.datePrecision))throw Error('Неверная дата');if(f.valueKind==='text'&&!f.valueText)throw Error('Пустое значение');if(f.valueKind==='number'&&f.valueNumber===undefined)throw Error('Нет числа');if(f.valueKind==='boolean'&&f.valueBoolean===undefined)throw Error('Нет значения Да/Нет');const old=existing.facts.find(x=>x.id===f.id);if(old&&(old.entityId!==f.entityId||old.key!==f.key||old.valueKind!==f.valueKind))throw Error('ID факта нельзя переназначать');if(old&&!allowUpdate&&JSON.stringify(old)!==JSON.stringify(f))throw Error('Факт с этим ID уже существует. Используйте редактор.')}
 for(const t of b.tags){let current:string|undefined=t.id;const seen=new Set<string>();while(current){if(seen.has(current))throw Error('Цикл в тегах');seen.add(current);const tag=tagMap.get(current);if(!tag)throw Error('Неизвестный родительский тег');current=tag.parentId}}
 for(const m of b.media)if(!e.has(m.entityId)||(!m.sourceUrl&&m.origin!=='user'))throw Error('Изображение без объекта или источника');for(const t of b.entityTags)if(!e.has(t.entityId)||!tagMap.has(t.tagId))throw Error('Неизвестный тег или объект');return b;
}
