import {z} from 'zod';
import {db,type EngiDB} from '../db/engi-db';
import {APP_DB_VERSION} from '../db/migrations';
import {learningRow} from '../db/repositories';
import {manifestSchema} from './pack-format';
const date=z.union([z.string(),z.date()]).refine(x=>Number.isFinite(new Date(x).getTime()));
const count=z.number().int().nonnegative();
export const memorySchema=z.object({id:z.string().min(1).max(500),card:z.object({due:date,stability:z.number().finite().nonnegative(),difficulty:z.number().finite().min(0).max(10),elapsed_days:z.number().finite().nonnegative(),scheduled_days:z.number().finite().nonnegative(),reps:count,lapses:count,state:z.number().int().min(0).max(3),learning_steps:count,last_review:date.optional()}).passthrough(),attempts:count,correct:count,firstSuccessAt:date.optional(),confusions:z.record(count)}).passthrough().refine(m=>m.correct<=m.attempts);
const eventSchema=z.object({id:z.string().min(1).max(500),timestamp:z.string().refine(x=>Number.isFinite(new Date(x).getTime())),recipe:z.string(),level:z.string(),targetIds:z.array(z.string()).default([]),payload:z.unknown()});
const backupSchema=z.object({format:z.literal('engi-backup'),schemaVersion:z.literal(1),appDbVersion:z.number().int().min(1).max(APP_DB_VERSION),exportedAt:z.string().datetime({offset:true}),learningState:z.array(z.object({id:z.string(),payload:memorySchema})),reviewEvents:z.array(eventSchema),installedPacks:z.array(manifestSchema.passthrough()),settings:z.record(z.unknown()),confusions:z.record(z.record(count))});
export async function exportBackup(d:EngiDB=db){return d.transaction('r',d.learningState,d.reviewEvents,d.installedPacks,d.appMeta,async()=>({format:'engi-backup' as const,schemaVersion:1,appDbVersion:APP_DB_VERSION,exportedAt:new Date().toISOString(),learningState:await d.learningState.toArray(),reviewEvents:await d.reviewEvents.orderBy('timestamp').toArray(),installedPacks:await d.installedPacks.toArray(),settings:Object.fromEntries((await d.appMeta.toArray()).map(r=>[r.key,r.value])),confusions:Object.fromEntries((await d.learningState.toArray()).map(r=>[r.id,r.payload.confusions]))}))}
export async function restoreBackup(input:unknown,d:EngiDB=db){const backup=backupSchema.parse(input);if(new Set(backup.learningState.map(r=>r.id)).size!==backup.learningState.length||new Set(backup.reviewEvents.map(e=>e.id)).size!==backup.reviewEvents.length)throw Error('Повтор ID в копии');for(const r of backup.learningState)if(r.id!==r.payload.id)throw Error('ID состояния не совпадает');
 await d.transaction('rw',d.learningState,d.reviewEvents,d.appMeta,d.activeSessions,async()=>{for(const r of backup.learningState)await d.learningState.put(learningRow(r.payload as any));for(const e of backup.reviewEvents){const old=await d.reviewEvents.get(e.id);if(old&&JSON.stringify(old.payload)!==JSON.stringify(e.payload))throw Error('Конфликт ID истории');if(!old)await d.reviewEvents.add(e as any)}for(const [key,value] of Object.entries(backup.settings))await d.appMeta.put({key,value});await d.appMeta.put({key:'restoredPackMetadata',value:backup.installedPacks});await d.appMeta.put({key:'lastBackupAt',value:backup.exportedAt});await d.appMeta.put({key:'reviewsSinceBackup',value:0});const active=await d.activeSessions.where('status').equals('active').toArray();for(const s of active)await d.activeSessions.update(s.id,{status:'completed'})});return backup.learningState.length}
export async function saveBackup(){const data=await exportBackup();const name=`engi-backup-${new Date().toISOString().slice(0,10)}.engi-backup`;const file=new File([JSON.stringify(data)],name,{type:'application/json'});let shared=false;if(navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file],title:'Резервная копия Энги'});shared=true}catch(e){if((e as Error).name==='AbortError')return;}}
 if(!shared){const url=URL.createObjectURL(file);const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)}await db.appMeta.bulkPut([{key:'lastBackupAt',value:new Date().toISOString()},{key:'reviewsSinceBackup',value:0}])}
