import {ZipReader,BlobReader,BlobWriter,TextWriter,configure,type Entry} from '@zip.js/zip.js';
import {db,type EngiDB,type PackRow} from '../db/engi-db';
import {factValue} from '../lib/engi/knowledge/properties';
import {upstreamFingerprint} from '../lib/engi/knowledge/conflicts';
import {getBundle,putBundle,contentTables} from '../db/repositories';
import {validateImport} from '../lib/engi/validate';
import {mediaStore} from '../media/media-store';
import {manifestSchema,safePath,sha256,checkImage,MAX_PACK_BYTES,MAX_MEDIA_BYTES} from './pack-format';
configure({useWebWorkers:typeof Worker!=='undefined'});
const jsonEntry=async(e:Entry|undefined)=>{if(!e||e.directory||e.uncompressedSize>16*1024*1024)throw Error('Нет JSON или он слишком большой');return JSON.parse(await e.getData!(new TextWriter(),{checkSignature:true}))};
export async function importPackDirect(file:Blob,onProgress:(s:string)=>void=()=>{},d:EngiDB=db){
 if(file.size>MAX_PACK_BYTES)throw Error('Пакет больше 512 МБ. Разделите его на несколько.');const reader=new ZipReader(new BlobReader(file));
 try{onProgress('Проверяем структуру пакета…');const entries=await reader.getEntries();const byPath=new Map<string,Entry>();let total=0;if(entries.length>50010)throw Error('Слишком много файлов');
 for(const e of entries){const path=e.directory?e.filename.replace(/\/$/,''):e.filename;if(!safePath(path)||byPath.has(e.filename)||e.encrypted)throw Error('Недопустимый ZIP path, дубль или шифрование');byPath.set(e.filename,e);if(!e.directory){total+=e.uncompressedSize;if(total>MAX_PACK_BYTES||e.uncompressedSize>16*1024*1024||e.uncompressedSize/Math.max(e.compressedSize,1)>100)throw Error('Превышен размер или подозрительное сжатие ZIP')}}
 const manifest=manifestSchema.parse(await jsonEntry(byPath.get('manifest.json')));const raw=await jsonEntry(byPath.get('bundle.json'));const files=new Map(manifest.files.map(f=>[f.path,f]));if(files.size!==manifest.files.length)throw Error('Повтор пути в manifest');for(const e of entries)if(!e.directory&&!['manifest.json','bundle.json'].includes(e.filename)&&!files.has(e.filename))throw Error('Незаявленный файл в ZIP');
 if(manifest.schemaVersion===1&&((raw.properties?.length??0)||(raw.entityTypes?.length??0)))throw Error('Новые поля требуют schemaVersion 2');const current=await getBundle(d);const bundle=validateImport(raw,current,true);for(const f of bundle.facts)if(!f.source.url)throw Error('Факты в пакете должны иметь HTTPS-источник');for(const m of bundle.media){const f=files.get(m.url);if(!f)throw Error('Каждое изображение должно ссылаться на файл внутри этого пакета');m.url='engi-media://'+f.sha256}
 let n=0;for(const f of manifest.files){const e=byPath.get(f.path);if(!e||e.directory||e.uncompressedSize!==f.bytes||f.bytes>MAX_MEDIA_BYTES)throw Error('Размер файла не совпадает с manifest');onProgress(`Проверяем изображения ${++n} / ${manifest.files.length}`);const blob=await e.getData!(new BlobWriter(f.mime),{checkSignature:true});if(blob.size!==f.bytes||await sha256(blob)!==f.sha256)throw Error('SHA-256 не совпадает');await checkImage(blob,f.mime)}
 const estimate=await globalThis.navigator?.storage?.estimate?.();const missing=[];for(const f of manifest.files)if(!await mediaStore.has(f.sha256))missing.push(f);const needed=missing.reduce((v,f)=>v+f.bytes,0);if(estimate?.quota&&estimate.quota-(estimate.usage??0)<needed*1.15+1024*1024)throw Error('Недостаточно места. Освободите память или импортируйте меньший пакет.');
 n=0;for(const f of missing){onProgress(`Сохраняем изображения ${++n} / ${missing.length}`);const entry=byPath.get(f.path)!;if(entry.directory)throw Error('Изображение не файл');const blob=await entry.getData!(new BlobWriter(f.mime),{checkSignature:true});await mediaStore.put(f.sha256,blob);}
 onProgress('Сохраняем набор…');await d.transaction('rw',[...contentTables(d),d.activeSessions,d.learningState],async()=>{const existing=await getBundle(d);validateImport(bundle,existing,true);const prior=await d.installedPacks.get(manifest.packId);if(prior&&manifest.packVersion<prior.packVersion)throw Error('Пакет старее установленной версии');const others=(await d.installedPacks.toArray()).filter(p=>p.packId!==manifest.packId);
 // A shared released ID has one meaning across packs; never silently reassign it.
 for(const f of bundle.facts)if(others.some(p=>p.factIds.includes(f.id))){const old=existing.facts.find(x=>x.id===f.id);if(old&&!old.userModified&&factValue(old)!==factValue(f))throw Error('Общий факт конфликтует с другим пакетом')}
 // Preserve user overlays and tombstones; removed upstream rows are archived, never erase history.
 const merge=(rows:any[],oldRows:any[])=>rows.map(row=>{const old=oldRows.find(o=>o.id===row.id);if(old?.userModified||old?.origin==='user'){const incoming=upstreamFingerprint(row),differs=upstreamFingerprint(old)!==incoming,conflict=differs&&old.upstreamAcknowledged!==incoming;return {...old,upstreamConflict:conflict,upstreamValue:conflict?row:undefined}}return {...row,origin:'pack',originPackId:manifest.packId,originPackVersion:manifest.packVersion}});
 const merged={...bundle};for(const key of ['entities','facts','media','tags','properties','entityTypes'] as const)(merged as any)[key]=merge(bundle[key]??[],existing[key]??[]);
 merged.entityTags=bundle.entityTags.map(row=>{const old=existing.entityTags.find(o=>o.entityId===row.entityId&&o.tagId===row.tagId);return old?.userModified?old:{...row,origin:'pack',originPackId:manifest.packId,originPackVersion:manifest.packVersion}});
 if(prior){for(const [key,table] of [['entityIds',d.entities],['factIds',d.facts],['mediaIds',d.media],['tagIds',d.tags]] as const){const nextIds=new Set((key==='entityIds'?bundle.entities:key==='factIds'?bundle.facts:key==='mediaIds'?bundle.media:bundle.tags).map(x=>x.id));for(const id of prior[key].filter(id=>!nextIds.has(id)&&!others.some(p=>p[key].includes(id)))){const old=await table.get(id);if(old&&!old.userModified&&old.origin!=='user')await (table as any).put({...old,archived:true})}}}
 for(const f of merged.facts){const old=existing.facts.find(x=>x.id===f.id);if(old&&factValue(old)!==factValue(f)){const keys=await d.learningState.filter(r=>r.id.startsWith(`fact:${f.id}:`)).primaryKeys();await d.learningState.bulkDelete(keys)}}await putBundle(d,merged);const row:PackRow={...manifest,entityIds:bundle.entities.map(x=>x.id),factIds:bundle.facts.map(x=>x.id),mediaIds:bundle.media.map(x=>x.id),tagIds:bundle.tags.map(x=>x.id),entityTags:bundle.entityTags,installedAt:new Date().toISOString()};await d.installedPacks.put(row);const active=await d.activeSessions.where('status').equals('active').toArray();for(const session of active)await d.activeSessions.update(session.id,{status:'completed'})});return {entities:bundle.entities.length,facts:bundle.facts.length,name:manifest.name}
 }finally{await reader.close()}
}

export async function importPack(file:Blob,onProgress:(s:string)=>void=()=>{},d:EngiDB=db,signal?:AbortSignal){
 if(d!==db||typeof Worker==='undefined')return importPackDirect(file,onProgress,d);
 return new Promise<Awaited<ReturnType<typeof importPackDirect>>>((resolve,reject)=>{const worker=new Worker(new URL('./pack-worker.ts',import.meta.url),{type:'module'});let committing=false;const done=()=>{worker.terminate();signal?.removeEventListener('abort',abort)};const abort=()=>{if(committing){onProgress('Завершаем сохранение набора…');return}done();reject(new DOMException('Импорт отменён','AbortError'))};signal?.addEventListener('abort',abort,{once:true});if(signal?.aborted){abort();return}worker.onmessage=e=>{if(e.data.progress){if(e.data.progress==='Сохраняем набор…')committing=true;onProgress(e.data.progress)}else if(e.data.error){done();reject(Error(e.data.error))}else if(e.data.result){done();resolve(e.data.result)}};worker.onerror=e=>{done();reject(Error(e.message||'Ошибка обработки пакета'))};worker.postMessage(file)});
}
