import {db,type EngiDB,type SessionRow,type LocalTask,type ReviewEventRow} from '../db/engi-db';
import {getSnapshot,getBundle,putBundle,learningRow,contentTables} from '../db/repositories';
import {generateSession,assess,updateMemory} from '../lib/engi/engine';
import {composeFeed,repairTask,cooled} from '../lib/engi/session/composer';
import {saveEntity} from './knowledge-service';
import {validateImport} from '../lib/engi/validate';
export function createTrainerService(d:EngiDB){return {
 getSnapshot:()=>getSnapshot(d),
 async startFeed(tag='all',format='mixed',mode='daily'){
 const s=await getSnapshot(d);const tasks=composeFeed(s.bundle,s.memories,tag,format,mode);if(!tasks.length)throw Error('Пока недостаточно подходящих знаний. Добавьте объекты или выберите другой формат.');const now=new Date().toISOString();const session:SessionRow={id:crypto.randomUUID(),tasks,currentPosition:0,results:[],mode,createdAt:now,updatedAt:now,status:'active',timeLeft:90,feed:true,tag,format,completedCount:0,cooldown:[],repairQueue:[]};await d.transaction('rw',d.activeSessions,async()=>{await d.activeSessions.where('status').equals('active').modify({status:'completed'});await d.activeSessions.put(session)});return session},
 async advanceFeed(id:string,skip=false){return d.transaction('rw',[d.activeSessions,d.entities,d.facts,d.tags,d.entityTags,d.media,d.propertyDefinitions,d.entityTypes,d.learningState],async()=>{const s=await d.activeSessions.get(id);if(!s?.feed)throw Error('Лента не найдена');const task=s.tasks[s.currentPosition];if(task){s.cooldown=[...s.cooldown??[],task].slice(-12);s.completedCount=(s.completedCount??0)+1;s.currentPosition++}const remaining=s.tasks.slice(s.currentPosition);if(remaining.length<6){const b=await getBundle(d);const memories=(await d.learningState.toArray()).map(r=>r.payload);const fresh=composeFeed(b,memories,s.tag,s.format,s.mode,[...s.cooldown??[],...remaining],12-remaining.length,s.completedCount);s.tasks.push(...fresh)}
 const repairs=s.repairQueue??[];const ready=repairs.find(t=>(t.retryAfter??0)<=(s.completedCount??0)&&cooled(t.items[0],s.cooldown??[]));if(ready){const tail=s.tasks.slice(s.currentPosition);const filtered:LocalTask[]=[];for(const t of tail){if(filtered.length<3&&t.items.some(i=>!cooled(i,[ready,...filtered])))continue;filtered.push(t)}s.tasks=[...s.tasks.slice(0,s.currentPosition),ready,...filtered];s.repairQueue=repairs.filter(t=>t.id!==ready.id)}
 // Bound session payload and preserve only the current buffer plus recent cooldowns.
 if(s.currentPosition>24){s.tasks=s.tasks.slice(s.currentPosition);s.currentPosition=0}s.updatedAt=new Date().toISOString();await d.activeSessions.put(s);return s})},

 async startSession(tag='all',format='mixed',mode='daily'){
 const s=await getSnapshot(d);const tasks:LocalTask[]=generateSession(s.bundle,s.memories,tag,format,mode).map(t=>({...t,...(t.recipe.format==='missing'?{sequence:[...t.items].sort((a,b)=>a.year!-b.year!).map((i,n)=>n===1?null:{name:i.name,entityId:i.entityId})}:{})}));if(!tasks.length)throw Error('Для этого режима недостаточно проверенных данных. Импортируйте пакет или выберите другой формат.');
 const now=new Date().toISOString();const session:SessionRow={id:crypto.randomUUID(),tasks,currentPosition:0,results:[],mode,createdAt:now,updatedAt:now,status:'active',timeLeft:90};await d.transaction('rw',d.activeSessions,async()=>{const active=await d.activeSessions.where('status').equals('active').toArray();for(const old of active)await d.activeSessions.update(old.id,{status:'completed'});await d.activeSessions.put(session)});return session},
 async getResumableSession(){return (await d.activeSessions.where('status').equals('active').sortBy('updatedAt')).at(-1)},
 async getFeedback(taskId:string){return (await d.reviewEvents.get(taskId))?.payload.feedback??null},
 async saveSession(id:string,changes:Partial<Pick<SessionRow,'currentPosition'|'timeLeft'|'status'>>){await d.activeSessions.update(id,{...changes,updatedAt:new Date().toISOString()})},
 async answer(input:{sessionId:string;taskId:string;answer:unknown;confidence?:string;latencyMs?:number}){
 return d.transaction('rw',d.learningState,d.reviewEvents,d.activeSessions,d.appMeta,async()=>{
 const duplicate=await d.reviewEvents.get(input.taskId);if(duplicate)return {feedback:duplicate.payload.feedback,memories:await d.learningState.bulkGet(duplicate.targetIds),event:duplicate,results:(await d.activeSessions.get(input.sessionId))?.results??[]};
 const session=await d.activeSessions.get(input.sessionId);const task=session?.tasks.find(t=>t.id===input.taskId);if(!task||!session)throw Error('Задание не найдено');
 const result=assess(task,input.answer);const confidence=['low','medium','high'].includes(input.confidence??'')?input.confidence!:'medium';
 const changes=[];const fsrsUpdated=new Set<string>();for(const evidence of result.evidence.filter(e=>e.level==='direct')){const old=await d.learningState.get(evidence.item.targetId);const quickRepair=!!task.retryOf&&!!old&&new Date(old.payload.card.due).getTime()>Date.now();let m=quickRepair?structuredClone(old!.payload):updateMemory(old?.payload,evidence.item,evidence.correct,evidence.chosen,confidence,task.recipe.format);if(!m)continue;if(!quickRepair)fsrsUpdated.add(evidence.item.targetId);if(quickRepair){m.attempts++;if(evidence.correct)m.correct++;else if(evidence.chosen)m.confusions[evidence.chosen]=(m.confusions[evidence.chosen]??0)+1;}if(evidence.correct)for(const o of task.options){if(o.id!==evidence.item.answerId&&m.confusions[o.id])m.confusions[o.id]*=.85;}
 if(!old){const prior=await d.reviewEvents.where('targetIds').equals(m.id).toArray();for(const event of prior)for(const p of event.payload.targets??[]){if(p.targetId===m.id&&!p.correct&&p.level==='direct'){if(p.chosen)m.confusions[p.chosen]=(m.confusions[p.chosen]||0)+1;m.attempts++}}}
 const row=learningRow(m);await d.learningState.put(row);changes.push(row)}
 const feedback={...result,chosen:input.answer,items:task.items,nextReview:changes[0]?.payload.card.due};const event:ReviewEventRow={id:task.id,timestamp:new Date().toISOString(),recipe:task.recipe.id,level:task.recipe.diagnostic?'diagnostic':task.recipe.format==='match'?'partial':'direct',targetIds:task.items.map(i=>i.targetId),payload:{score:result.score,reason:task.reason,pretest:!changes.length&&!task.recipe.diagnostic,selfReport:task.recipe.format==='recall_reveal',fsrsEnabled:fsrsUpdated.size>0,targets:result.evidence.map(e=>({targetId:e.item.targetId,correct:e.correct,chosen:e.chosen,level:e.level,fsrsUpdated:fsrsUpdated.has(e.item.targetId)})),latencyMs:Math.min(3600000,Math.max(0,input.latencyMs??0)),confidence,feedback}};
 if(session.feed&&!task.recipe.diagnostic&&result.score<1&&!task.retryOf){const failed=result.evidence.findIndex(e=>!e.correct);const repair=repairTask(task,Math.max(0,failed));repair.retryAfter=(session.completedCount??0)+4;session.repairQueue=[...session.repairQueue??[],repair]};
 await d.reviewEvents.add(event);session.results.push(result.score);if(session.results.length>100)session.results=session.results.slice(-100);session.updatedAt=event.timestamp;await d.activeSessions.put(session);
 const counter=await d.appMeta.get('reviewsSinceBackup');await d.appMeta.put({key:'reviewsSinceBackup',value:(counter?.value??0)+1});return {feedback,memories:changes,event,results:session.results};})},
 async createRetry(sessionId:string,taskId:string){return d.transaction('rw',d.activeSessions,d.reviewEvents,async()=>{const session=await d.activeSessions.get(sessionId);const original=session?.tasks.find(t=>t.id===taskId);const event=await d.reviewEvents.get(taskId);if(!session||!original||!event)throw Error('Сначала проверьте ответ');let probe=session.tasks.find(t=>t.retryOf===taskId);if(!probe){const failed=event.payload.targets?.find((e:any)=>!e.correct);const item=original.items.find(i=>i.targetId===failed?.targetId)??original.items.at(-1)!;probe={id:crypto.randomUUID(),retryOf:original.id,recipe:{...original.recipe,id:original.recipe.id.replace(/:[^:]+$/,':recall'),format:'recall',diagnostic:false},items:[item],options:[],reason:'Повтор после других заданий'};const pos=session.tasks.findIndex(t=>t.id===taskId);session.tasks.splice(Math.min(pos+3,session.tasks.length),0,probe);await d.activeSessions.put(session)}return {task:probe,tasks:session.tasks}})},
 async importBundle(input:unknown){return d.transaction('rw',contentTables(d),async()=>{const b=validateImport(input,await getBundle(d));if(b.media.some(m=>!m.url.startsWith('engi-media://')))throw Error('Изображения должны быть локальными. Используйте .engi с media внутри.');await putBundle(d,b);return {entities:b.entities.length,facts:b.facts.length,excluded:b.facts.filter(f=>!['direct','verified'].includes(f.verification)).length}})},
 async editEntity(input:{entityId:string;name:string;facts:any[]}){const b=await getBundle(d);const e=b.entities.find(e=>e.id===input.entityId);if(!e)throw Error('Объект не найден');const facts=input.facts.map(change=>{const f=b.facts.find(x=>x.id===change.id);if(!f)throw Error('Факт не найден');const next={...f,...change};if(f.valueKind==='date'&&change.year!==undefined&&String(change.year)!==f.dateStart?.slice(0,4)){const y=Number(change.year);if(!Number.isInteger(y)||y<1||y>2100)throw Error('Неверный год');next.dateStart=String(y).padStart(4,'0')+'-01-01';next.dateEnd=String(y).padStart(4,'0')+'-12-31';next.datePrecision='year'}return next});await saveEntity({...e,name:input.name},facts,b.entityTags.filter(t=>t.entityId===e.id&&!t.archived).map(t=>t.tagId),d);return {ok:true}},
 async reportQuestion(taskId:string,reason:string){if(!reason.trim())throw Error('Опишите ошибку');await d.reviewEvents.add({id:crypto.randomUUID(),timestamp:new Date().toISOString(),recipe:'report',level:'report',targetIds:[],payload:{taskId,reason:reason.slice(0,1000)}})},
 async resolveReport(reportId:string){return d.transaction('rw',d.reviewEvents,async()=>{if(!(await d.reviewEvents.get(reportId)))throw Error('Сообщение не найдено');if(!(await d.reviewEvents.get('resolved:'+reportId)))await d.reviewEvents.add({id:'resolved:'+reportId,timestamp:new Date().toISOString(),recipe:'report_resolved',level:'report',targetIds:[],payload:{reportId}})})}
}}
export const trainerService=createTrainerService(db);
