import {db,type EngiDB,type SessionRow,type LocalTask,type ReviewEventRow} from '../db/engi-db';
import {getSnapshot,getBundle,putBundle,learningRow,contentTables} from '../db/repositories';
import {generateSession,assess,updateMemory} from '../lib/engi/engine';
import {validateImport} from '../lib/engi/validate';
export function createTrainerService(d:EngiDB){return {
 getSnapshot:()=>getSnapshot(d),
 async startSession(tag='all',format='mixed',mode='daily'){
 const s=await getSnapshot(d);const tasks:LocalTask[]=generateSession(s.bundle,s.memories,tag,format,mode).map(t=>({...t,...(t.recipe.format==='missing'?{sequence:[...t.items].sort((a,b)=>a.year!-b.year!).map((i,n)=>n===1?null:{name:i.name,entityId:i.entityId})}:{})}));if(!tasks.length)throw Error('Для этого режима недостаточно проверенных данных. Импортируйте пакет или выберите другой формат.');
 const now=new Date().toISOString();const session:SessionRow={id:crypto.randomUUID(),tasks,currentPosition:0,results:[],mode,createdAt:now,updatedAt:now,status:'active',timeLeft:90};await d.transaction('rw',d.activeSessions,async()=>{const active=await d.activeSessions.where('status').equals('active').toArray();for(const old of active)await d.activeSessions.update(old.id,{status:'completed'});await d.activeSessions.put(session)});return session},
 async getResumableSession(){return (await d.activeSessions.where('status').equals('active').sortBy('updatedAt')).at(-1)},
 async getFeedback(taskId:string){return (await d.reviewEvents.get(taskId))?.payload.feedback??null},
 async saveSession(id:string,changes:Partial<Pick<SessionRow,'currentPosition'|'timeLeft'|'status'>>){await d.activeSessions.update(id,{...changes,updatedAt:new Date().toISOString()})},
 async answer(input:{sessionId:string;taskId:string;answer:unknown;confidence?:string;latencyMs?:number}){
 return d.transaction('rw',d.learningState,d.reviewEvents,d.activeSessions,d.appMeta,async()=>{
 const duplicate=await d.reviewEvents.get(input.taskId);if(duplicate)return {feedback:duplicate.payload.feedback,memories:await d.learningState.bulkGet(duplicate.targetIds),event:duplicate,results:(await d.activeSessions.get(input.sessionId))?.results??[]};
 const session=await d.activeSessions.get(input.sessionId);const task=session?.tasks.find(t=>t.id===input.taskId);if(!task||!session)throw Error('Задание не найдено');
 const result=assess(task,input.answer);const confidence=['low','medium','high'].includes(input.confidence??'')?input.confidence!:'medium';
 const changes=[];for(const evidence of result.evidence.filter(e=>e.level==='direct')){const old=await d.learningState.get(evidence.item.targetId);const m=updateMemory(old?.payload,evidence.item,evidence.correct,evidence.chosen,confidence,task.recipe.format);if(!m)continue;
 if(!old){const prior=await d.reviewEvents.where('targetIds').equals(m.id).toArray();for(const event of prior)for(const p of event.payload.targets??[]){if(p.targetId===m.id&&!p.correct&&p.level==='direct'){if(p.chosen)m.confusions[p.chosen]=(m.confusions[p.chosen]||0)+1;m.attempts++}}}
 const row=learningRow(m);await d.learningState.put(row);changes.push(row)}
 const feedback={...result,items:task.items,nextReview:changes[0]?.payload.card.due};const event:ReviewEventRow={id:task.id,timestamp:new Date().toISOString(),recipe:task.recipe.id,level:task.recipe.diagnostic?'diagnostic':task.recipe.format==='match'?'partial':'direct',targetIds:task.items.map(i=>i.targetId),payload:{score:result.score,targets:result.evidence.map(e=>({targetId:e.item.targetId,correct:e.correct,chosen:e.chosen,level:e.level})),latencyMs:Math.min(3600000,Math.max(0,input.latencyMs??0)),confidence,feedback}};
 await d.reviewEvents.add(event);session.results.push(result.score);session.updatedAt=event.timestamp;await d.activeSessions.put(session);
 const counter=await d.appMeta.get('reviewsSinceBackup');await d.appMeta.put({key:'reviewsSinceBackup',value:(counter?.value??0)+1});return {feedback,memories:changes,event,results:session.results};})},
 async createRetry(sessionId:string,taskId:string){return d.transaction('rw',d.activeSessions,d.reviewEvents,async()=>{const session=await d.activeSessions.get(sessionId);const original=session?.tasks.find(t=>t.id===taskId);const event=await d.reviewEvents.get(taskId);if(!session||!original||!event)throw Error('Сначала проверьте ответ');let probe=session.tasks.find(t=>t.retryOf===taskId);if(!probe){const failed=event.payload.targets?.find((e:any)=>!e.correct);const item=original.items.find(i=>i.targetId===failed?.targetId)??original.items.at(-1)!;probe={id:crypto.randomUUID(),retryOf:original.id,recipe:{...original.recipe,id:original.recipe.id.replace(/:[^:]+$/,':recall'),format:'recall',diagnostic:false},items:[item],options:[],reason:'Повтор после других заданий'};const pos=session.tasks.findIndex(t=>t.id===taskId);session.tasks.splice(Math.min(pos+3,session.tasks.length),0,probe);await d.activeSessions.put(session)}return {task:probe,tasks:session.tasks}})},
 async importBundle(input:unknown){return d.transaction('rw',contentTables(d),async()=>{const b=validateImport(input,await getBundle(d));if(b.media.some(m=>!m.url.startsWith('engi-media://')))throw Error('Изображения должны быть локальными. Используйте .engi с media внутри.');await putBundle(d,b);return {entities:b.entities.length,facts:b.facts.length,excluded:b.facts.filter(f=>!['direct','verified'].includes(f.verification)).length}})},
 async editEntity(input:{entityId:string;name:string;facts:any[]}){return d.transaction('rw',d.entities,d.facts,d.learningState,d.activeSessions,async()=>{const entity=await d.entities.get(input.entityId);if(!entity||!input.name.trim()||input.name.length>200)throw Error('Проверьте название');const selected=await d.facts.where('entityId').equals(entity.id).toArray();const changedFacts=[];
 for(const change of input.facts){const f=selected.find(f=>f.id===change.id);if(!f)throw Error('Факт не найден');const next={...f,verification:change.verification};if(f.valueKind==='entity')next.valueEntityId=change.valueEntityId;if(f.valueKind==='text')next.valueText=change.valueText;if(f.valueKind==='number')next.valueNumber=Number(change.valueNumber??change.valueText);if(f.valueKind==='date'&&String(change.year)!==f.dateStart?.slice(0,4)){const y=Number(change.year);if(!Number.isInteger(y)||y<1||y>2100)throw Error('Неверный год');next.dateStart=String(y).padStart(4,'0')+'-01-01';next.dateEnd=String(y).padStart(4,'0')+'-12-31';next.datePrecision='year'}changedFacts.push(next)}
 const entities=await d.entities.toArray();validateImport({entities,facts:changedFacts,media:[]},{entities,facts:[],media:[],tags:[],entityTags:[],missing:[],unresolved:[]});await d.entities.put({...entity,name:input.name.trim()});for(const next of changedFacts){const old=selected.find(f=>f.id===next.id)!;const values=(f:typeof old)=>JSON.stringify([f.valueEntityId,f.valueText,f.valueNumber,f.dateStart,f.dateEnd,f.datePrecision]);if(values(old)!==values(next)){const ids=await d.learningState.filter(r=>r.id.startsWith(`fact:${next.id}:`)).primaryKeys();await d.learningState.bulkDelete(ids)}await d.facts.put(next)}const active=await d.activeSessions.where('status').equals('active').toArray();for(const session of active)await d.activeSessions.update(session.id,{status:'completed'});return {ok:true}})},
 async reportQuestion(taskId:string,reason:string){if(!reason.trim())throw Error('Опишите ошибку');await d.reviewEvents.add({id:crypto.randomUUID(),timestamp:new Date().toISOString(),recipe:'report',level:'report',targetIds:[],payload:{taskId,reason:reason.slice(0,1000)}})},
 async resolveReport(reportId:string){return d.transaction('rw',d.reviewEvents,async()=>{if(!(await d.reviewEvents.get(reportId)))throw Error('Сообщение не найдено');if(!(await d.reviewEvents.get('resolved:'+reportId)))await d.reviewEvents.add({id:'resolved:'+reportId,timestamp:new Date().toISOString(),recipe:'report_resolved',level:'report',targetIds:[],payload:{reportId}})})}
}}
export const trainerService=createTrainerService(db);
