import assert from 'node:assert/strict';
import {chromium} from 'playwright';
const browser=await chromium.launch({headless:true,executablePath:process.env.ENGI_BROWSER_PATH}),context=await browser.newContext({viewport:{width:393,height:852}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(10000);
try{await page.goto(process.env.ENGI_TEST_URL??'http://127.0.0.1:5175/engi/');await page.locator('.feed-home').waitFor();
 const setup=await page.evaluate(async()=>{const {db}=await import('/engi/src/db/engi-db.ts'),{putBundle,getBundle}=await import('/engi/src/db/repositories.ts'),{trainerService}=await import('/engi/src/services/trainer-service.ts'),{canonicalTargets}=await import('/engi/src/lib/engi/questions/recipe-factory.ts'),{goalProposalPool}=await import('/engi/src/services/goal-proposals.ts'),{groupProposals}=await import('/engi/src/services/group-candidates.ts'),{prepareStudyTask}=await import('/engi/src/services/study-core-bridge.ts');if(await db.learningState.count()||await db.activeSessions.count())throw Error('Requires empty ephemeral browser');
 const b={entities:[],facts:[],media:[],tags:[],entityTags:[],missing:[],unresolved:[],entityTypes:[{id:'city',name:'Город'},{id:'country',name:'Страна'}],properties:[{id:'country',name:'Страна',valueKind:'entity',cardinality:'one',learnable:true,subjectTypes:['city'],targetTypes:['country']},{id:'year',name:'Основание',valueKind:'date',cardinality:'one',learnable:true,subjectTypes:['city']}]};for(let n=0;n<6;n++){b.entities.push({id:'e'+n,type:'city',name:'Город '+n,aliases:[],externalIds:{}});b.facts.push({id:'country'+n,entityId:'e'+n,key:'country',valueKind:'entity',valueEntityId:n%2?'usa':'fr',verification:'user_confirmed',source:{kind:'manual',name:'Test'}},{id:'year'+n,entityId:'e'+n,key:'year',valueKind:'date',dateStart:(1700+n*50)+'-01-01',dateEnd:(1700+n*50)+'-12-31',datePrecision:'year',verification:'user_confirmed',source:{kind:'manual',name:'Test'}});}b.entities.push({id:'usa',type:'country',name:'США',aliases:[],externalIds:{}},{id:'fr',type:'country',name:'Франция',aliases:[],externalIds:{}});await putBundle(db,b);let s=await trainerService.startGoalFeed('all','mixed','daily',{endless:true});const bundle=await getBundle(db);for(let n=0;n<6;n++){s.intro={entityId:'e'+n,unitIds:canonicalTargets(bundle).filter(i=>i.entityId==='e'+n).map(i=>i.targetId),selections:{},newProperty:false};await db.activeSessions.put(s);s=await trainerService.completeIntro(s.id);}
 const enabled=(await db.learningState.toArray()).map(r=>r.payload),pool=goalProposalPool(bundle,enabled,'all','mixed'),p=groupProposals(pool.proposals.filter(p=>p.recipe.format==='categorize'),new Set(),12,{conveyor:true})[0];if(!p)throw Error('Missing conveyor group');const task={id:crypto.randomUUID(),memoryModel:'goals',learningLifecycle:1,presentation:'conveyor',recipe:p.recipe,items:p.items,options:p.options,reason:'bootstrap',intent:'learn'};s.tasks=[task];s.intro=undefined;s.exhausted=false;s.interaction=undefined;s.currentPosition=0;await prepareStudyTask(db,bundle,task);await db.activeSessions.put(s);return {id:s.id,task};});
 await page.reload();await page.getByRole('button',{name:'Продолжить с прошлого места',exact:true}).click();await page.locator('.feed-conveyor').waitFor();await page.locator('.study-feed.state-ready').waitFor();
 const firstId=await page.locator('.conveyor-object').getAttribute('data-conveyor-id'),item=setup.task.items.find(i=>i.entityId===firstId),wrong=setup.task.options.find(o=>o.id!==item.answerId);await page.getByRole('button',{name:wrong.name,exact:false}).click();await page.locator('.conveyor-status.wrong').waitFor();await page.waitForFunction(id=>document.querySelector('.conveyor-object')?.dataset.conveyorId!==id,firstId);
 // The wrong object is queued behind other objects; first failure is already saved.
 assert.equal(await page.evaluate(async()=>{const {db}=await import('/engi/src/db/engi-db.ts');return (await db.appMeta.where('key').startsWith('studyCore:mistakeEpisodes').toArray()).length>0;}),true);
 await page.waitForFunction(()=>Math.abs(new DOMMatrix(getComputedStyle(document.querySelector('.conveyor-object')).transform).m41)<2);
 const secondId=await page.locator('.conveyor-object').getAttribute('data-conveyor-id'),second=setup.task.items.find(i=>i.entityId===secondId),correctIndex=setup.task.options.findIndex(o=>o.id===second.answerId),box=await page.locator('.conveyor-object').boundingBox();await page.mouse.move(box.x+box.width/2,box.y+50);await page.mouse.down();await page.mouse.move(box.x+box.width/2+(correctIndex===0?-110:110),box.y+50,{steps:8});await page.mouse.up();await page.waitForFunction(id=>document.querySelector('.conveyor-object')?.dataset.conveyorId!==id,secondId);
 await page.reload();await page.getByRole('button',{name:'Продолжить с прошлого места',exact:true}).click();await page.locator('.feed-conveyor').waitFor();await page.locator('.study-feed.state-ready').waitFor();await page.waitForFunction(()=>[...document.querySelectorAll('.conveyor-category')].every(b=>!b.disabled));assert.notEqual(await page.locator('.conveyor-object').getAttribute('data-conveyor-id'),secondId);
 await page.setViewportSize({width:320,height:736});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=320));await page.screenshot({path:'artifacts/conveyor-mobile.png'});
 const sort=await page.evaluate(async sid=>{const {db}=await import('/engi/src/db/engi-db.ts'),{getBundle}=await import('/engi/src/db/repositories.ts'),{goalProposalPool}=await import('/engi/src/services/goal-proposals.ts'),{buildLearningChronology}=await import('/engi/src/services/learning-chronology.ts'),{prepareStudyTask}=await import('/engi/src/services/study-core-bridge.ts');const b=await getBundle(db),enabled=(await db.learningState.toArray()).map(r=>r.payload),p=goalProposalPool(b,enabled).proposals.filter(p=>p.recipe.format==='choice'&&p.items[0].factId?.startsWith('year')),task=buildLearningChronology(b,p,[],[],0);const s=await db.activeSessions.get(sid);s.tasks=[task];s.interaction=undefined;await prepareStudyTask(db,b,task);await db.activeSessions.put(s);return task;},setup.id);
 await page.reload();await page.getByRole('button',{name:'Продолжить с прошлого места',exact:true}).click();await page.locator('.feed-sort').waitFor();assert.equal(await page.locator('input[type=range]').count(),0);
 const rows=page.locator('.sort-row'),last=await rows.last().getAttribute('data-item'),from=await rows.last().boundingBox(),to=await rows.first().boundingBox();await page.mouse.move(from.x+45,from.y+from.height/2);await page.mouse.down();await page.mouse.move(to.x+45,to.y+2,{steps:12});await page.mouse.up();assert.equal(await rows.first().getAttribute('data-item'),last);
 // Use accessible move controls to set the correct order, then submit.
 const expected=[...sort.items].sort((a,b)=>a.year-b.year).map(i=>i.entityId);for(let n=0;n<expected.length;n++){while(await rows.nth(n).getAttribute('data-item')!==expected[n]){await page.locator(`[data-item="${expected[n]}"]`).getByRole('button',{name:/Выше/}).click();}}
 await page.screenshot({path:'artifacts/chronology-order-mobile.png'});await page.getByRole('button',{name:'Проверить порядок',exact:true}).click();await page.getByText('Верный порядок ✓',{exact:true}).waitFor();
 await page.evaluate(async({sid,source})=>{const {db}=await import('/engi/src/db/engi-db.ts'),{getBundle}=await import('/engi/src/db/repositories.ts'),{prepareStudyTask}=await import('/engi/src/services/study-core-bridge.ts');const items=source.items.map((item,n)=>{const c=document.createElement('canvas');c.width=n%2?320:120;c.height=n%2?120:240;const x=c.getContext('2d');x.fillStyle=n%2?'#e0aa67':'#426f95';x.fillRect(0,0,c.width,c.height);x.fillStyle='#fff';x.font='40px sans-serif';x.fillText(String(n+1),20,60);return {...item,image:c.toDataURL(),mediaId:undefined};});const t={...source,id:crypto.randomUUID(),items,recipe:{...source.recipe,cue:'image'},studyContract:undefined,practice:true,intent:'practice'};const s=await db.activeSessions.get(sid);s.tasks=[t];s.interaction=undefined;s.intro=undefined;s.exhausted=false;s.currentPosition=0;await prepareStudyTask(db,await getBundle(db),t);await db.activeSessions.put(s);},{sid:setup.id,source:setup.task});
 await page.reload();await page.getByRole('button',{name:'Продолжить с прошлого места',exact:true}).click();await page.locator('.conveyor-object img').waitFor();await page.waitForFunction(()=>document.querySelector('.conveyor-object img')?.naturalWidth>0&&[...document.querySelectorAll('.conveyor-category')].every(b=>!b.disabled));const imageBox=await page.locator('.conveyor-object img').boundingBox();assert(imageBox.x>=0&&imageBox.x+imageBox.width<=320);await page.screenshot({path:'artifacts/conveyor-image-mobile.png'});
 assert.deepEqual(errors,[]);console.log('PASS conveyor wrong queue, swipe, reload, 320px, images; vertical drag, buttons, order submission; no slider');
}finally{await context.close();await browser.close();}
