import 'fake-indexeddb/auto';
import {test} from 'node:test';import assert from 'node:assert/strict';
import {parseV3} from '../src/lib/engi/import/schema-v3';import {buildImportPlan} from '../src/lib/engi/import/semantic-merge';
import {canonicalTargets,eligible,recipes} from '../src/lib/engi/questions/recipe-factory';import {composeUnit} from '../src/lib/engi/session/composer';import {allowedMedia} from '../src/lib/engi/questions/exemplar-selector';
import {compileTaskContract,identityGoal} from '../src/lib/engi/study-core/compiler';import {createStudyCoreService} from '../src/services/study-core-service';import {validateImport} from '../src/lib/engi/validate';
import {EngiDB} from '../src/db/engi-db';import {putBundle,getBundle} from '../src/db/repositories';import {exportBackup,restoreBackup} from '../src/services/backup-service';import type {Task} from '../src/lib/engi/types';
const empty={entities:[],facts:[],media:[],tags:[],entityTags:[],missing:[],unresolved:[]};
function fixture(){return parseV3({schemaVersion:3,name:'Flags',properties:[{name:'Флаг',valueType:'image',subjectTypes:['Штат']}],entities:Array.from({length:4},(_,n)=>({name:'State '+n,type:'Штат',images:[{file:'media/map'+n+'.png',role:'image',primary:true,recognition:true,license:'Test',sourceUrl:'https://example.org/maps'},{file:'media/flag'+n+'.png',role:'property',recognition:false,license:'Test',sourceUrl:'https://example.org/flags'}],facts:[{property:'Флаг',value:{file:'media/flag'+n+'.png'},source:{kind:'manual',name:'Test'},verification:'user_confirmed'}]})),deck:{name:'States',members:Array.from({length:4},(_,n)=>({name:'State '+n,type:'Штат'})),learning:{properties:['Флаг'],imageRecognition:true}}});}
function data(){return buildImportPlan(fixture(),empty,{},'flags').bundle;}
function task(imageAnswer=false){const b=data(),r=recipes(b).find(r=>r.format==='choice'&&r.answerKey!=='identity'&&(r.answerPresentation==='image')===imageAnswer)!,items=eligible(b,r);const t:Task={id:crypto.randomUUID(),memoryModel:'goals',recipe:r,items:[items[0]],options:items.map(i=>({id:i.answerId,name:i.answer,...(imageAnswer?{image:i.answerImage,mediaId:i.answerMediaId}:{})})),reason:'test'};return {b,t};}
test('image property imports a real owned media reference and rejects missing or unrelated files',()=>{const b=data();assert.equal(b.facts.filter(f=>f.valueKind==='image').length,4);for(const f of b.facts)assert(b.media.some(m=>m.id===f.valueMediaId&&m.entityId===f.entityId));const p=fixture();p.entities[0].facts[0].value={file:'media/missing.png'};assert.throws(()=>buildImportPlan(p,empty));const copy=structuredClone(b);copy.facts[0].valueMediaId=copy.media.find(m=>m.entityId!==copy.facts[0].entityId)!.id;assert.throws(()=>validateImport(copy,empty,true));});
test('maps and flag associations are distinct targets; property images never rotate into identity cues',()=>{const b=data(),targets=canonicalTargets(b);assert.equal(targets.filter(i=>i.factId).length,4);assert.equal(targets.filter(i=>!i.factId).length,4);const r=recipes(b).find(r=>r.answerKey==='identity')!;for(const entity of b.entities){assert(allowedMedia(b,entity.id,r).every(m=>m.url.includes('map')));assert.notEqual(targets.find(i=>i.entityId===entity.id&&i.factId)!.targetId,targets.find(i=>i.entityId===entity.id&&!i.factId)!.targetId);}});
test('flag-to-state and state-to-flag formats share the property goal but not the map goal',()=>{const a=task(),z=task(true),c=compileTaskContract(a.b,a.t),d=compileTaskContract(z.b,z.t);assert.equal(c.primaryGoals[0].id,d.primaryGoals[0].id);assert.notEqual(c.primaryGoals[0].id,identityGoal(a.b,a.t.items[0].entityId,'recognition').id);assert.equal(c.shownClaims.length,0);assert(a.t.items[0].image!.includes('flag'));assert(z.t.options.every(o=>o.image?.includes('flag')));const m={id:z.t.items[0].targetId,card:{},attempts:0,correct:0,confusions:{},status:'learning' as const};let found=false;for(let n=0;n<30;n++){const t=composeUnit(z.b,m);if(t?.recipe.answerPresentation==='image'){assert(t.options.every(o=>o.image));compileTaskContract(z.b,t);found=true;break;}}assert(found);});
test('image matching contracts grade flags as property facts and reject changed cached pictures',()=>{const {b,t}=task();const r=recipes(b).find(r=>r.format==='match'&&r.answerKey!=='identity')!,items=eligible(b,r).slice(0,3),group={...t,recipe:r,items,options:items.map(i=>({id:i.answerId,name:i.answer}))},c=compileTaskContract(b,group);assert.equal(c.primaryGoals.length,3);assert(c.primaryGoals.every(g=>g.knowledge.kind==='fact'));const stale=structuredClone(t);stale.items[0].image='media/map0.png';assert.throws(()=>compileTaskContract(b,stale));const wrong=task(true);wrong.t.options[0].image='media/map0.png';assert.throws(()=>compileTaskContract(wrong.b,wrong.t));});
test('flag success creates only flag memory and repeated submissions cannot seed map memory',async()=>{const {b,t}=task(),d=new EngiDB('flag-memory-'+crypto.randomUUID());try{const c=compileTaskContract(b,t),core=createStudyCoreService(d,{applyMemory:true});await core.setContentRevisions(c.contentRevisions);await core.open(c,t.id,new Date(0));const result=await core.submit(t.id,t.items[0].answerId,new Date(1000));assert(result.results![0].credit);await core.submit(t.id,t.items[0].answerId,new Date(2000));assert.equal(await d.appMeta.where('key').startsWith('studyCore:memory:').count(),1);assert.equal(await core.memory(identityGoal(b,t.items[0].entityId,'recognition').id),undefined);}finally{d.close();await d.delete();}});
test('reimport is idempotent and adds a new property to a default existing deck',()=>{const p=fixture(),first=buildImportPlan(p,empty,{},'first');const second=buildImportPlan(p,first.bundle,{deck:first.deckId!},'second');assert.equal(second.bundle.facts.length,first.bundle.facts.length);assert.deepEqual(second.bundle.facts.map(f=>f.id),first.bundle.facts.map(f=>f.id));const old=fixture();old.properties=[];old.entities.forEach(e=>e.facts=[]);old.deck!.learning.properties=[];const base=buildImportPlan(old,empty,{},'old'),up=buildImportPlan(p,base.bundle,{deck:base.deckId!},'up');assert(up.bundle.decks![0].learning.propertyIds!.includes(up.bundle.properties!.find(p=>p.valueKind==='image')!.id));});
test('image facts and their references survive a backup restore',async()=>{const d=new EngiDB('flag-backup-'+crypto.randomUUID()),other=new EngiDB('flag-restored-'+crypto.randomUUID());try{await putBundle(d,data());const backup=await exportBackup(d);await restoreBackup(backup,other);const b=await getBundle(other);assert.equal(b.facts.filter(f=>f.valueKind==='image').length,4);assert.equal(canonicalTargets(b).filter(i=>i.factId).length,4);}finally{d.close();other.close();await d.delete();await other.delete();}});

test('image import preserves explicit deck choices and replaces secondary generic images without duplicating media',()=>{const old=fixture();old.properties=[];old.entities.forEach(e=>{e.facts=[];e.images.forEach(i=>i.role='image');});old.deck!.learning.properties=[];const base=buildImportPlan(old,empty,{},'old');base.bundle.decks![0].userModified=true;const up=buildImportPlan(fixture(),base.bundle,{deck:base.deckId!},'up');assert.deepEqual(up.bundle.decks![0].learning.propertyIds,[]);assert.equal(up.bundle.media.length,8);assert.equal(up.bundle.media.filter(m=>m.role==='property').length,4);});
