import {buildSelfCheck} from '../src/services/self-check-composition';
import 'fake-indexeddb/auto';import {test} from 'node:test';import assert from 'node:assert/strict';
import {groupProposals} from '../src/services/group-candidates';import {buildLearningChronology} from '../src/services/learning-chronology';import {compileTaskContract,associationGoal} from '../src/lib/engi/study-core/compiler';import {EngiDB} from '../src/db/engi-db';import {createStudyCoreService} from '../src/services/study-core-service';import {admitAcquisition,emptyLifecycle,ACQUISITION_CONFIRMATION_MS} from '../src/lib/engi/study-core/acquisition';import {putBundle,learningRow} from '../src/db/repositories';import {triagedMemory} from '../src/lib/engi/learning/bootstrap';import {canonicalTargets} from '../src/lib/engi/questions/recipe-factory';import {buildGoalCatalog} from '../src/services/goal-catalog';import {pickLifecycleFeed} from '../src/services/lifecycle-feed-service';import type {Bundle,Task} from '../src/lib/engi/types';
const b:Bundle={entities:Array.from({length:9},(_,n)=>({id:'e'+n,name:'Event '+n,type:'event',aliases:[],externalIds:{}})),facts:Array.from({length:9},(_,n)=>({id:'f'+n,entityId:'e'+n,key:'year',valueKind:'date',dateStart:(1700+n*10)+'-01-01',dateEnd:(1700+n*10)+'-12-31',datePrecision:'year',source:{kind:'manual',name:'Test'},verification:'user_confirmed'})),media:[],tags:[],entityTags:[],missing:[],unresolved:[],properties:[{id:'year',name:'Year',valueKind:'date',cardinality:'one',learnable:true,subjectTypes:['event']}]};
const proposals=b.facts.map(f=>({recipe:{id:'test',format:'match' as const,cue:'name' as const,answerKey:'year',memoryKey:'year',diagnostic:false},items:[{entityId:f.entityId,name:f.entityId,targetId:'t'+f.id,factId:f.id,year:Number(f.dateStart!.slice(0,4)),answer:f.id,answerId:f.id,aliases:[],sourceUrl:''}],goals:[associationGoal(b,f,'recognition')]}));
test('matching requires three distinct objects and never fills an undersized group',()=>{assert.equal(groupProposals(b,proposals.slice(0,2),new Set(),6).length,0);assert.equal(groupProposals(b,proposals,new Set(),2).length,0);const groups=groupProposals(b,proposals,new Set(),6);assert(groups.length);assert(groups.every(g=>g.items.length>=3));});
test('binary conveyor has 3–6 objects, repeated categories are allowed but object duplicates are not',()=>{const p=proposals.map((p,n)=>({...p,recipe:{...p.recipe,format:'categorize' as const},items:p.items.map(i=>({...i,answerId:n%2?'right':'left',answer:n%2?'Right':'Left'}))}));assert.equal(groupProposals(b,p.slice(0,2),new Set(),6,{conveyor:true}).length,0);for(const count of [3,4,6,9]){const groups=groupProposals(b,p.slice(0,count),new Set(),12,{conveyor:true});assert(groups.length);assert(groups.every(g=>g.items.length>=3&&g.items.length<=6&&new Set(g.items.map(i=>i.entityId)).size===g.items.length));}});
test('date boundary conveyor also refuses two objects and caps its group at six',()=>{const p=proposals.map(p=>({...p,recipe:{...p.recipe,format:'choice' as const}})),history=[{recipe:{format:'sort'}} as Task];assert.equal(buildLearningChronology(b,p.slice(0,2),[],history,0),undefined);const t=buildLearningChronology(b,p,[],history,0)!;assert.equal(t.presentation,'conveyor');assert(t.items.length>=3&&t.items.length<=6);});
test('timed learning rehearsal never seeds recall memory or graduates recognition; a later objective answer is required',async()=>{const d=new EngiDB('rehearsal-'+crypto.randomUUID());try{const goal=associationGoal(b,b.facts[0],'recognition');await d.appMeta.put({key:'studyCore:learningLifecycle',value:admitAcquisition(emptyLifecycle(),'e0',[goal],new Date(0))});const item=proposals[0].items[0],t:Task={id:'timed',learningRecall:true,learningLifecycle:1,memoryModel:'goals',intent:'learn',recipe:{...proposals[0].recipe,format:'recall_reveal'},items:[item],options:[],reason:'rehearsal'},c=compileTaskContract(b,t),core=createStudyCoreService(d,{lifecycle:true});assert(c.learningRecall);await core.setContentRevisions(c.contentRevisions);await core.open(c,t.id,new Date(0));await core.observe(t.id,'answer-reveal','own-answer','start',new Date(5000));const a=await core.submit(t.id,true,new Date(6000));assert(a.results!.every(r=>!r.credit&&!r.acquisitionCredit));assert.equal(await d.appMeta.where('key').startsWith('studyCore:memory:').count(),0);const ledger=(await d.appMeta.get('studyCore:learningLifecycle'))!.value;assert.equal(ledger.units.length,1);assert.equal(ledger.units[0].goal.id,goal.id);assert.equal(ledger.units[0].stage,'confirmation');assert.equal(ledger.units[0].requiredSuccesses,1);assert.equal(new Date(ledger.units[0].availableAt).getTime(),6000+ACQUISITION_CONFIRMATION_MS);await core.submit(t.id,true,new Date(7000));assert.deepEqual((await d.appMeta.get('studyCore:learningLifecycle'))!.value,ledger);
 const direct:Task={...t,id:'objective',learningRecall:undefined,recipe:{...t.recipe,format:'choice'},options:proposals.slice(0,3).map(p=>({id:p.items[0].answerId,name:p.items[0].answer}))},dc=compileTaskContract(b,direct);await core.setContentRevisions(dc.contentRevisions);await core.open(dc,direct.id,new Date(6000+ACQUISITION_CONFIRMATION_MS));const final=await core.submit(direct.id,item.answerId,new Date(6001+ACQUISITION_CONFIRMATION_MS));assert(final.results![0].credit);assert.equal(await d.appMeta.where('key').startsWith('studyCore:memory:').count(),1);
 }finally{d.close();await d.delete();}});
test('mixed lifecycle selection offers a timer among initial properties instead of filtering its recall skill out',async()=>{const d=new EngiDB('rehearsal-select-'+crypto.randomUUID());try{await putBundle(d,b);const targets=canonicalTargets(b);for(const item of targets)await d.learningState.put(learningRow(triagedMemory(item,'red','seed',0)));const enabled=(await d.learningState.toArray()).map(r=>r.payload),catalog=buildGoalCatalog(b,enabled);let ledger=emptyLifecycle();for(const e of b.entities)ledger=admitAcquisition(ledger,e.id,catalog.filter(c=>c.entityIds.includes(e.id)).map(c=>c.goal),new Date(0));await d.appMeta.put({key:'studyCore:learningLifecycle',value:ledger});await d.appMeta.put({key:'studyPreferences',value:{newCardsPerDay:0}});const s:any={id:'variety',tasks:[],currentPosition:0,results:[],mode:'daily',memoryModel:'goals',learningLifecycle:1,endless:true,format:'mixed',tag:'all',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),status:'active',timeLeft:0,cooldown:Array.from({length:5},(_,n)=>({id:'history'+n,recipe:{format:'choice'},items:[{entityId:'e8',factId:'f8'}],reason:'bootstrap',options:[]}))};const result=await pickLifecycleFeed(d,b,enabled,s,{day:'test',introducedEntityIds:b.entities.map(e=>e.id),extraBudget:0},b.entities.map(e=>e.id));assert.equal(result.task?.recipe.format,'recall_reveal');assert(result.task?.learningRecall);assert.notEqual(result.task?.items[0].entityId,'e8');assert.equal((await d.appMeta.get('studyCore:learningLifecycle'))!.value.units.length,9);
 }finally{d.close();await d.delete();}});

test('self-check groups use only ready distinct objects and have no grading goals',async()=>{const ready=proposals.map(p=>({...p,recipe:{...p.recipe,format:'choice' as const}}));assert.equal(buildSelfCheck(b,ready.slice(0,2)),undefined);const t=buildSelfCheck(b,ready)!;assert.equal(t.items.length,4);const c=compileTaskContract(b,t);assert.equal(c.response.kind,'practice-view');assert.equal(c.primaryGoals.length,0);const d=new EngiDB('view-credit-'+crypto.randomUUID());try{let ledger=emptyLifecycle();for(const p of proposals)ledger=admitAcquisition(ledger,p.items[0].entityId,p.goals,new Date(0));await d.appMeta.put({key:'studyCore:learningLifecycle',value:ledger});const core=createStudyCoreService(d,{lifecycle:true});await core.setContentRevisions(c.contentRevisions);await core.open(c,t.id,new Date(0));await core.observe(t.id,`card-reveal:${t.items[0].entityId}`,'first-card','start',new Date(1000));const exposed=await d.appMeta.where('key').startsWith('studyCore:exposure:').toArray();assert(exposed.every(row=>row.value.goalId.includes(t.items[0].factId!)));const after=(await d.appMeta.get('studyCore:learningLifecycle'))!.value;assert.equal(after.units.length,ledger.units.length);assert(after.units[0].selfCheckedAt);assert(!after.units[1].selfCheckedAt);const answer=await core.submit(t.id,true,new Date(1500));assert.deepEqual(answer.results,[]);assert.equal(await d.appMeta.where('key').startsWith('studyCore:memory:').count(),0);await assert.rejects(core.observe(t.id,'card-reveal:unknown','bad','start',new Date(2000)));}finally{d.close();await d.delete();}});

test('self-check image fronts do not depend on which direction the choice generator selected',()=>{
 const bundle={...b,properties:[{...b.properties![0],valueKind:'image' as const}]};
 const ready=proposals.slice(0,4).map((p,n)=>({...p,recipe:{...p.recipe,format:'choice' as const,cue:n%2?'name' as const:'image' as const,answerPresentation:n%2?'image' as const:undefined},items:p.items.map(i=>({...i,image:n%2?undefined:'flag'+n,answerImage:'flag'+n}))}));
 const t=buildSelfCheck(bundle,ready)!;assert.equal(t.items.length,4);assert.equal(t.recipe.cue,'image');assert.deepEqual(t.items.map(i=>i.image),['flag0','flag1','flag2','flag3']);
});
test('mixed feed schedules a self-check from ready properties without adding learning obligations',async()=>{
 const d=new EngiDB('grid-select-'+crypto.randomUUID());try{await putBundle(d,b);for(const item of canonicalTargets(b))await d.learningState.put(learningRow(triagedMemory(item,'red','seed',0)));const enabled=(await d.learningState.toArray()).map(r=>r.payload),catalog=buildGoalCatalog(b,enabled);let ledger=emptyLifecycle();for(const e of b.entities)ledger=admitAcquisition(ledger,e.id,catalog.filter(c=>c.entityIds.includes(e.id)).map(c=>c.goal),new Date(0));await d.appMeta.put({key:'studyCore:learningLifecycle',value:ledger});await d.appMeta.put({key:'studyPreferences',value:{newCardsPerDay:0}});
 const s:any={id:'grid',tasks:[],currentPosition:0,results:[],mode:'daily',memoryModel:'goals',learningLifecycle:1,endless:true,format:'mixed',tag:'all',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),status:'active',timeLeft:0,cooldown:Array.from({length:9},(_,n)=>({id:'h'+n,recipe:{format:'choice'},items:[{entityId:'e8',factId:'f8'}],reason:'bootstrap',options:[]}))};
 const result=await pickLifecycleFeed(d,b,enabled,s,{day:'test',introducedEntityIds:b.entities.map(e=>e.id),extraBudget:0},b.entities.map(e=>e.id));assert.equal(result.task?.recipe.format,'self_check');assert.equal(result.task?.items.length,4);assert(!result.task?.items.some(i=>i.entityId==='e8'));assert.deepEqual((await d.appMeta.get('studyCore:learningLifecycle'))!.value,ledger);
 }finally{d.close();await d.delete();}
});
test('incorrect and hinted timed rehearsals cannot promote a property or raise memory',async()=>{
 for(const hinted of [false,true]){const d=new EngiDB('rehearsal-safe-'+crypto.randomUUID());try{const goal=associationGoal(b,b.facts[0],'recognition');await d.appMeta.put({key:'studyCore:learningLifecycle',value:admitAcquisition(emptyLifecycle(),'e0',[goal],new Date(0))});const t:Task={id:'timer',learningRecall:true,learningLifecycle:1,memoryModel:'goals',intent:'learn',recipe:{...proposals[0].recipe,format:'recall_reveal'},items:[proposals[0].items[0]],options:[],reason:'rehearsal'},c=compileTaskContract(b,t),core=createStudyCoreService(d,{lifecycle:true});await core.setContentRevisions(c.contentRevisions);await core.open(c,t.id,new Date(0));if(hinted)await core.observe(t.id,'early-answer','hint','start',new Date(1000));else await core.observe(t.id,'answer-reveal','normal','start',new Date(5000));const a=await core.submit(t.id,hinted,new Date(6000));assert(a.results!.every(r=>!r.credit&&!r.contextCredit));const unit=(await d.appMeta.get('studyCore:learningLifecycle'))!.value.units[0];assert.equal(unit.stage,'first-check');assert.equal(unit.requiredSuccesses,2);assert.equal(unit.successes,0);assert.equal(await d.appMeta.where('key').startsWith('studyCore:memory:').count(),0);}finally{d.close();await d.delete();}}
});

