import 'fake-indexeddb/auto';
import Dexie from 'dexie';
import {State} from 'ts-fsrs';
import assert from 'node:assert/strict';
import {test} from 'node:test';
import {readFile} from 'node:fs/promises';
import {EngiDB} from '../src/db/engi-db';
import {storesV1} from '../src/db/migrations';
import {getBundle,getSnapshot,putBundle,emptyBundle,contentTables,learningRow} from '../src/db/repositories';
import {saveKnowledge,saveEntity,saveProperty,saveTag,uploadImage} from '../src/services/knowledge-service';
import {importPack} from '../src/services/pack-service';
import {exportBackup,restoreBackup} from '../src/services/backup-service';
import {createTrainerService} from '../src/services/trainer-service';
import {recipes,eligible,canonicalTargets} from '../src/lib/engi/questions/recipe-factory';
import {composeFeed,cooled} from '../src/lib/engi/session/composer';
import {updateMemory,preflight,assess} from '../src/lib/engi/engine';
import {sha256} from '../src/services/pack-format';
import {ZipWriter,BlobWriter,BlobReader,TextReader,configure} from '@zip.js/zip.js';
import {prepareDue} from './helpers22';
import type {Bundle,PropertyDefinition,Fact} from '../src/lib/engi/types';
configure({useWebWorkers:false});
const cache=new Map<string,Response>();Object.defineProperty(globalThis,'caches',{value:{open:async()=>({match:async(k:string)=>cache.get(k)?.clone(),put:async(k:string,r:Response)=>cache.set(k,r.clone()),delete:async(k:string)=>cache.delete(k)}),keys:async()=>['engi-media-v1']},configurable:true});
const seed:Bundle=JSON.parse(await readFile(new URL('./fixtures/seed.json',import.meta.url),'utf8'));
const image=new Blob([await readFile(new URL('../public/icon-192.png',import.meta.url))],{type:'image/png'});const hash=await sha256(image);
async function withDB(run:(d:EngiDB)=>Promise<void>){const d=new EngiDB('v2-'+crypto.randomUUID());try{await run(d)}finally{d.close();await d.delete()}}
function dynamic():Bundle{const b=emptyBundle();b.entityTypes=[{id:'custom.actor',name:'Актёр'},{id:'custom.place',name:'Город'}];b.properties=[{id:'custom.birth_place',name:'Место рождения',valueKind:'entity',subjectTypes:['custom.actor'],targetTypes:['custom.place'],cardinality:'one',learnable:true}];for(let i=0;i<5;i++){b.entities.push({id:'p'+i,type:'custom.actor',name:'Человек '+i,aliases:[],externalIds:{}},{id:'c'+i,type:'custom.place',name:'Город '+i,aliases:[],externalIds:{}});b.facts.push({id:'f'+i,entityId:'p'+i,key:'custom.birth_place',valueKind:'entity',valueEntityId:'c'+i,source:{kind:'manual',name:'Личное знание'},verification:'user_confirmed'})}return b}
async function zip(b:Bundle,version=1,schemaVersion=1){const raw=structuredClone(b);raw.media=raw.media.map(m=>({...m,url:'media/icon.png'}));const manifest={format:'engi-pack',schemaVersion,packId:'starter',packVersion:version,name:'Starter',createdAt:new Date().toISOString(),files:raw.media.length?[{path:'media/icon.png',bytes:image.size,sha256:hash,mime:'image/png'}]:[]};const w=new ZipWriter(new BlobWriter());await w.add('manifest.json',new TextReader(JSON.stringify(manifest)));await w.add('bundle.json',new TextReader(JSON.stringify(raw)));if(raw.media.length)await w.add('media/icon.png',new BlobReader(image),{level:0});return w.close()}

test('v1 → v2 migration preserves entities, facts, exact learning IDs, events, packs and media',async()=>{const name='migration-'+crypto.randomUUID();const old=new Dexie(name);old.version(1).stores(storesV1);const b=structuredClone(seed);b.media=b.media.map(m=>({...m,url:'engi-media://'+hash}));const r=recipes(b).find(r=>r.answerKey==='created_by'&&r.format==='choice')!;const item=eligible(b,r)[0];const memory=updateMemory(undefined,item,true,item.answerId)!;await old.table('entities').bulkPut(b.entities);await old.table('facts').bulkPut(b.facts);await old.table('media').bulkPut(b.media);await old.table('learningState').put(learningRow(memory));await old.table('reviewEvents').put({id:'old-event',timestamp:new Date().toISOString(),recipe:'old',level:'direct',targetIds:[item.targetId],payload:{score:1}});await old.table('installedPacks').put({packId:'seed',packVersion:1,entityIds:b.entities.map(e=>e.id),factIds:b.facts.map(f=>f.id),mediaIds:b.media.map(m=>m.id),tagIds:[]});old.close();const migrated=new EngiDB(name);try{assert.equal(await migrated.entities.count(),32);assert.equal(await migrated.facts.count(),34);assert.equal(await migrated.media.count(),22);assert.deepEqual((await migrated.learningState.get(memory.id))?.payload,memory);assert.equal(await migrated.reviewEvents.count(),1);assert.equal(await migrated.installedPacks.count(),1);assert.equal(await migrated.propertyDefinitions.count(),11);assert.equal((await migrated.facts.get(b.facts[0].id))?.origin,'pack')}finally{migrated.close();await migrated.delete()}});

test('new type + property + relation generates valid choice without code; insufficient/ambiguous data is excluded',async()=>withDB(async d=>{await saveKnowledge(dynamic(),d);const b=await getBundle(d);const rs=recipes(b).filter(r=>r.answerKey==='custom.birth_place');assert(rs.some(r=>r.format==='choice'));await prepareDue(d);const tasks=composeFeed(b,(await getSnapshot(d)).memories,'all','choice','daily',[],12);assert(tasks.length>=4);for(const t of tasks){assert(preflight(t));assert.equal(assess(t,t.items[0].answerId).score,1)}const few=dynamic();few.entities=few.entities.slice(0,4);few.facts=few.facts.slice(0,2);assert(!recipes(few).some(r=>r.format==='choice'));const many=dynamic();many.properties![0].cardinality='many';many.facts.push({...many.facts[0],id:'second-author',valueEntityId:'c1'});const r=rs.find(r=>r.format==='choice')!;assert(!eligible(many,r).some(i=>i.entityId==='p0'));const conflicting=dynamic();conflicting.facts.push({...conflicting.facts[0],id:'conflict',valueEntityId:'c1'});assert(!eligible(conflicting,r).some(i=>i.entityId==='p0'))}));

test('rename and label preserve FSRS; value edit invalidates only dependent targets; tags and archives preserve history',async()=>withDB(async d=>{await saveKnowledge(dynamic(),d);let b=await getBundle(d);const rs=recipes(b).find(r=>r.answerKey==='custom.birth_place'&&r.format==='choice')!;const items=eligible(b,rs);for(const i of items.slice(0,2))await d.learningState.put(learningRow(updateMemory(undefined,i,true,i.answerId)!));await d.reviewEvents.put({id:'history',timestamp:new Date().toISOString(),recipe:'test',level:'direct',targetIds:[items[0].targetId],payload:{score:1}});const before=await d.learningState.toArray();await saveEntity({...b.entities.find(e=>e.id==='p0')!,name:'Переименован'},[],[],d);await saveProperty({...b.properties!.find(p=>p.id==='custom.birth_place')!,name:'Родной город'},d);assert.deepEqual(await d.learningState.toArray(),before);await saveTag({id:'custom.tag',name:'Моя подборка'},d);await saveKnowledge({entityTags:[{entityId:'p0',tagId:'custom.tag'}]},d);assert.equal((await d.entityTags.get(['p0','custom.tag']))?.origin,'user');await saveKnowledge({facts:[{...b.facts.find(f=>f.id==='f0')!,valueEntityId:'c2'}]},d);assert.equal(await d.learningState.count(),1);assert(await d.learningState.get(items[1].targetId));assert.equal(await d.reviewEvents.count(),1);await saveKnowledge({facts:[{...b.facts.find(f=>f.id==='f1')!,archived:true}]},d);assert.equal(await d.reviewEvents.count(),1)}));

test('v1 pack, user override, upstream update, removed row tombstone and v2 custom pack',async()=>withDB(async d=>{await importPack(await zip(seed),()=>{},d);let b=await getBundle(d);const f=b.facts.find(f=>f.key==='presidency_start')!;await saveKnowledge({facts:[{...f,dateStart:'1900-01-01',dateEnd:'1900-12-31',datePrecision:'year'}]},d);await importPack(await zip(seed,2),()=>{},d);const local=await d.facts.get(f.id);assert.equal(local?.dateStart,'1900-01-01');assert(local?.userModified);assert(local?.upstreamConflict);const removed=structuredClone(seed);removed.facts=removed.facts.filter(x=>x.id!==f.id);await importPack(await zip(removed,3),()=>{},d);assert.equal((await d.facts.get(f.id))?.dateStart,'1900-01-01');const custom=dynamic();custom.facts=custom.facts.map(f=>({...f,source:{name:'Source',url:'https://example.org'},verification:'verified'}));await importPack(await zip(custom,4,2),()=>{},d);assert(await d.propertyDefinitions.get('custom.birth_place'));assert(recipes(await getBundle(d)).some(r=>r.answerKey==='custom.birth_place'&&r.format==='choice'))}));

test('backup v2 restores user entities/relations/types/properties/tags/overrides and actual user image bytes; v1 remains accepted',async()=>withDB(async d=>{await saveKnowledge(dynamic(),d);await saveTag({id:'mine',name:'Мои знания'},d);await saveKnowledge({entityTags:[{entityId:'p0',tagId:'mine'}]},d);await uploadImage('p0',image,'portrait',d);const backup=JSON.parse(JSON.stringify(await exportBackup(d)));assert.equal(backup.schemaVersion,2);assert.equal(backup.userMedia.length,1);const target=new EngiDB('restore-'+crypto.randomUUID());try{await restoreBackup(backup,target);assert.equal(await target.facts.count(),5);assert.equal(await target.entities.count(),10);assert(await target.propertyDefinitions.get('custom.birth_place'));assert(await target.entityTypes.get('custom.actor'));assert(await target.entityTags.get(['p0','mine']));assert.equal(await target.media.count(),1);const legacy={...backup,schemaVersion:1,appDbVersion:1};delete legacy.userKnowledge;delete legacy.userMedia;await restoreBackup(legacy,target);assert.equal(await target.facts.count(),5);const corrupt=structuredClone(backup);corrupt.userMedia[0].hash='0'.repeat(64);await assert.rejects(restoreBackup(corrupt,target));assert.equal(await target.facts.count(),5)}finally{target.close();await target.delete()}}));

test('due builder avoids duplicate and unscheduled units while format controls preserve canonical targets',async()=>withDB(async d=>{
 const b=structuredClone(seed);b.media=b.media.map(m=>({...m,url:'engi-media://'+hash}));await d.transaction('rw',contentTables(d),()=>putBundle(d,b));await prepareDue(d);const memories=(await getSnapshot(d)).memories;
 const first=composeFeed(b,memories,'all','mixed','daily',[],12);assert.equal(first.length,12);for(const task of first)assert(preflight(task));assert.equal(new Set(first.map(t=>t.items[0].targetId)).size,first.length);
 const target=first[0].items[0].targetId,future=memories.map(m=>m.id===target?{...m,card:{...m.card,due:new Date(Date.now()+86400000)}}:m);
 assert(!composeFeed(b,future,'all','mixed','daily',[],memories.length).some(t=>t.items[0].targetId===target));
 assert(!composeFeed(b,memories,'all','mixed','daily',[first[0]],memories.length).some(t=>t.items[0].targetId===target));
 const dynamicB=dynamic(),total=canonicalTargets(dynamicB).length;dynamicB.properties![0].learning={choice:'off',recallReveal:'on'};assert.equal(canonicalTargets(dynamicB).length,total);assert(!recipes(dynamicB).some(r=>r.format==='choice'));
}));

test('feed atomic double submit, retry is delayed and established quick repair does not reschedule FSRS',async()=>withDB(async d=>{
 await saveKnowledge(dynamic(),d);await prepareDue(d);const service=createTrainerService(d),session=await service.startFeed('all','choice'),t=session.tasks[0],answer=t.items[0].answerId;
 await Promise.all([service.answer({sessionId:session.id,taskId:t.id,answer}),service.answer({sessionId:session.id,taskId:t.id,answer})]);assert.equal(await d.reviewEvents.count(),1);assert.equal((await d.learningState.get(t.items[0].targetId))?.payload.attempts,1);
 const next=await service.advanceFeed(session.id);assert.equal(next.completedCount,1);assert.equal(next.tasks.length,1);const original=next.tasks[0],m=updateMemory(undefined,original.items[0],true,original.items[0].answerId)!;m.status='review';m.card.state=State.Review;m.card.reps=3;m.card.last_review=new Date(Date.now()-86400000);m.card.due=new Date(Date.now()-1000);await d.learningState.put(learningRow(m));
 await service.answer({sessionId:session.id,taskId:original.id,answer:original.options.find(o=>o.id!==original.items[0].answerId)!.id});await service.answer({sessionId:session.id,taskId:original.id,answer:original.items[0].answerId});const afterFailure=(await d.learningState.get(m.id))!.payload;assert(afterFailure.card.lapses>m.card.lapses);
 const repairSession=(await d.activeSessions.get(session.id))!,pending=repairSession.repairQueue![0];assert.equal(pending.retryAfter,(repairSession.completedCount??0)+4);repairSession.tasks=[pending];repairSession.currentPosition=0;repairSession.repairQueue=[];await d.activeSessions.put(repairSession);
 await service.answer({sessionId:session.id,taskId:pending.id,answer:pending.items[0].answerId});const repaired=(await d.learningState.get(m.id))!.payload;assert.deepEqual(repaired.card,afterFailure.card);assert.equal(repaired.attempts,afterFailure.attempts);assert.equal((await d.reviewEvents.get(pending.id))?.payload.fsrsEnabled,false);assert.equal((await d.reviewEvents.get(pending.id))?.payload.reason,'retry');
 d.close();const reopened=new EngiDB(d.name);try{assert.equal((await createTrainerService(reopened).getResumableSession())?.id,session.id)}finally{reopened.close()}
}));

test('main feed stops when its due units finish and optional practice preserves scheduling',async()=>withDB(async d=>{
 await saveKnowledge(dynamic(),d);await prepareDue(d);const svc=createTrainerService(d);let session=await svc.startFeed('all','choice');const seen=new Set<string>();
 for(let n=0;n<5;n++){const task=session.tasks[0];assert(task);assert(!seen.has(task.items[0].targetId));seen.add(task.items[0].targetId);await svc.answer({sessionId:session.id,taskId:task.id,answer:task.items[0].answerId});session=await svc.advanceFeed(session.id)}
 assert.equal(session.exhausted,true);assert.equal(session.tasks.length,0);assert.equal(session.completedCount,5);assert.equal(await d.reviewEvents.count(),5);
 const before=await d.learningState.toArray();session=await svc.openMore(session.id,true);assert.equal(session.mode,'practice');const task=session.tasks[0];assert(task.practice);if(task.recipe.format==='recall_reveal')await svc.saveInteraction(session.id,task.id,{recallElapsedMs:5000,revealed:true});await svc.answer({sessionId:session.id,taskId:task.id,answer:task.recipe.format==='recall_reveal'?true:task.items[0].answerId});
 for(const row of before){const after=(await d.learningState.get(row.id))!.payload;assert.deepEqual(after.card,row.payload.card);assert.equal(after.attempts,row.payload.attempts)}assert.equal((await d.reviewEvents.get(task.id))!.level,'practice');
}));

test('automatic repair surfaces after unrelated cards and does not duplicate a future task',async()=>withDB(async d=>{
 await saveKnowledge(dynamic(),d);await prepareDue(d);const svc=createTrainerService(d);let s=await svc.startFeed('all','choice');const original=s.tasks[0];await svc.answer({sessionId:s.id,taskId:original.id,answer:original.options.find(o=>o.id!==original.items[0].answerId)!.id});await svc.answer({sessionId:s.id,taskId:original.id,answer:original.items[0].answerId});const failed=(await d.learningState.get(original.items[0].targetId))!.payload;
 assert.equal(failed.card.reps,0);assert.equal(failed.card.lapses,0);let found=false;for(let n=0;n<12;n++){s=await svc.advanceFeed(s.id);const task=s.tasks[0];assert(task);assert.equal(s.tasks.length,1);if(task.retryOf===original.id){assert((s.completedCount??0)>=4);assert(cooled(task.items[0],s.cooldown??[]));await svc.answer({sessionId:s.id,taskId:task.id,answer:task.items[0].answerId});assert.deepEqual((await d.learningState.get(original.items[0].targetId))!.payload.card,failed.card);s=await svc.advanceFeed(s.id);for(let remaining=0;s.tasks.length&&remaining<5;remaining++){const next=s.tasks[0];assert.notEqual(next.items[0].targetId,original.items[0].targetId);await svc.answer({sessionId:s.id,taskId:next.id,answer:next.items[0].answerId});s=await svc.advanceFeed(s.id)}assert.equal(s.tasks.length,0);assert.equal(s.exhausted,true);found=true;break}await svc.answer({sessionId:s.id,taskId:task.id,answer:task.items[0].answerId})}assert(found,'repair should actually appear');
}));
