import type {Bundle,Memory,Task,Item,Recipe} from '../types';
import {recipes,eligible} from '../questions/recipe-factory';
import {distractors} from '../questions/distractors';
import {shuffle,preflight} from '../engine';
export function cooled(i:Item,recent:Task[]){return !recent.slice(-3).some((t,n,a)=>t.items.some(x=>x.targetId===i.targetId||!!i.answerEntityId&&(x.answerEntityId===i.answerEntityId||x.entityId===i.answerEntityId)||x.answerEntityId===i.entityId||(a.length-n<=2&&(x.entityId===i.entityId||!!i.factId&&x.factId===i.factId))))}
export function composeFeed(b:Bundle,memories:Memory[],tag='all',format='mixed',mode='daily',recent:Task[]=[],count=12,completed=0):Task[]{
 const mem=new Map(memories.map(m=>[m.id,m]));const rs=recipes(b).filter(r=>(tag==='all'?r.tag===undefined:r.tag===tag)&&(format==='mixed'||r.format===format));const pools=new Map(rs.map(r=>[r.id,eligible(b,r)]));const targets=new Map<string,{item:Item;recipes:Recipe[]}>();for(const r of rs.filter(r=>!r.diagnostic))for(const i of pools.get(r.id)??[]){const entry=targets.get(i.targetId)??{item:i,recipes:[]};entry.recipes.push(r);targets.set(i.targetId,entry)}
 const dueCount=[...targets.keys()].filter(id=>mem.has(id)&&new Date(mem.get(id)!.card.due).getTime()<=Date.now()).length;const out:Task[]=[];
 for(let n=0;n<count;n++){const history=[...recent,...out];const lastChallenge=history.slice(-8).some(t=>t.recipe.diagnostic);const challenge=(format!=='mixed'&&rs.every(r=>r.diagnostic))||(format==='mixed'&&completed+history.length>=8&&!lastChallenge);
  let built:Task|undefined;
  if(challenge){for(const r of shuffle(rs.filter(r=>r.diagnostic))){const raw=shuffle(pools.get(r.id)??[]).filter(i=>cooled(i,history));const seen=new Set<number>();const items=raw.filter(i=>{if(i.year===undefined||seen.has(i.year))return false;seen.add(i.year);return true}).slice(0,4);if(items.length<3)continue;const t:Task={id:crypto.randomUUID(),recipe:r,items:r.format==='timeline'?[items[0]]:items,options:shuffle(items.map(i=>({id:i.entityId,name:i.name}))),reason:'challenge'};if(r.format==='missing'){const sorted=[...items].sort((a,c)=>a.year!-c.year!);t.sequence=sorted.map((i,n)=>n===1?null:{name:i.name,entityId:i.entityId})}if(preflight(t)){built=t;break}}}
  if(!built){const candidates=shuffle([...targets.values()]).filter(x=>cooled(x.item,history));const groups={due:candidates.filter(x=>{const m=mem.get(x.item.targetId);return m&&new Date(m.card.due).getTime()<=Date.now()}),weak:candidates.filter(x=>{const m=mem.get(x.item.targetId);return m&&(m.attempts>m.correct||Object.values(m.confusions).some(c=>c>.2))}),new:candidates.filter(x=>!mem.has(x.item.targetId))};
   const draw=Math.random();const prefer=mode==='weak'?'weak':mode==='explore'?'new':draw<(dueCount>30?.7:.55)?'due':draw<(dueCount>30?.85:.75)?'weak':'new';const ordered=[...new Set([prefer,'due','weak','new'])] as (keyof typeof groups)[];let selected=ordered.flatMap(k=>groups[k].map(x=>({...x,reason:k==='weak'&&(Object.values(mem.get(x.item.targetId)?.confusions??{}).some(c=>c>.2))?'confusion':k})));if(!selected.length)selected=candidates.map(x=>({...x,reason:'weak'}));
   for(const x of selected){const options=shuffle(x.recipes).sort((a,c)=>{const rank=(r:Recipe)=>r.format==='choice'?0:r.format==='recall_reveal'?1:2;return rank(a)-rank(c)});if(format==='mixed'&&Math.random()<.25)options.sort((a,c)=>Number(c.format==='recall_reveal')-Number(a.format==='recall_reveal'));
    for(const r of options){let item=x.item;const media=b.media.filter(m=>m.entityId===item.entityId&&!m.archived&&m.learningExemplar!==false);const m=mem.get(item.targetId);if(r.cue==='image'&&media.length>1&&m?.card.stability>=7)item={...item,image:shuffle(media)[0].url};const wrong=distractors(b,item,pools.get(r.id)??[],m,history);const t:Task={id:crypto.randomUUID(),recipe:r,items:[item],options:shuffle([{id:item.answerId,name:item.answer},...wrong]),reason:x.reason};if(r.format==='categorize')t.options=shuffle([{id:item.answerId,name:item.answer},...wrong]);if(preflight(t)){built=t;break}}if(built)break;
   }
  }
  if(!built)break;out.push(built);
 }return out;
}
export function repairTask(original:Task,index:number):Task{const item=original.items[index]??original.items[0];const format=original.recipe.format==='recall_reveal'&&original.options.length>=3?'choice':'recall_reveal';return {...original,id:crypto.randomUUID(),retryOf:original.id,reason:'retry',items:[item],recipe:{...original.recipe,id:original.recipe.id+':repair',format,diagnostic:false,evidence:{level:'direct',fsrsEnabled:true,gradeCap:'good',selfReport:format==='recall_reveal'},feed:{presentation:'atomic',autoAdvanceOnCorrect:true,correctHoldMs:280,maxOptions:4}}}}
