import type {Bundle,PropertyDefinition,EntityTypeDefinition,Fact} from '../types';
const specs:[string,string,PropertyDefinition['valueKind'],string[],string[]?][]=[['created_by','Автор','entity',['artwork','book','film','game'],['person']],['creation_date','Дата создания','date',['artwork','book','film','game']],['presidency_start','Начало президентства','date',['person']],['presidency_end','Конец президентства','date',['person']],['party','Партия','entity',['person'],['organization']],['movement','Направление','entity',['person','artwork'],['movement']],['birth_date','Дата рождения','date',['person']],['invented_by','Изобретатель','entity',['invention'],['person']],['event_start','Начало события','date',['event']],['capital','Столица','entity',['country'],['city']],['definition','Определение','text',['concept','invention']]];
export const BUILTIN_PROPERTIES:PropertyDefinition[]=specs.map(([id,name,valueKind,subjectTypes,targetTypes])=>({id,name,valueKind,subjectTypes,targetTypes,cardinality:['created_by','movement','invented_by'].includes(id)?'many':'one',learnable:valueKind!=='text',builtIn:true,inverse:{enabled:false},learning:{forward:true}}));
export const BUILTIN_TYPES:EntityTypeDefinition[]=[['person','Человек'],['artwork','Картина'],['country','Страна'],['city','Город'],['organization','Организация'],['movement','Направление'],['event','Событие'],['invention','Изобретение'],['concept','Понятие'],['film','Фильм'],['book','Книга'],['game','Игра']].map(([id,name])=>({id,name,builtIn:true}));
export function properties(b:Bundle){return [...new Map([...BUILTIN_PROPERTIES,...b.properties??[]].map(p=>[p.id,p])).values()].filter(p=>!p.archived)}
export function entityTypes(b:Bundle){return [...new Map([...b.entities.map(e=>({id:e.type,name:e.type})),...BUILTIN_TYPES,...b.entityTypes??[]].map(p=>[p.id,p])).values()]}
export const trusted=(f:Fact)=>!f.archived&&['direct','verified','user_confirmed'].includes(f.verification);
export const factValue=(f:Fact)=>JSON.stringify([f.valueKind,f.valueEntityId,...(f.valueKind==='image'?[f.valueMediaId]:[]),f.valueText,f.valueNumber,f.valueBoolean,f.dateStart,f.dateEnd,f.datePrecision,f.unit]);
export const textValue=(f:Fact,b:Bundle)=>f.valueKind==='image'?'Изображение':f.valueKind==='entity'?b.entities.find(e=>e.id===f.valueEntityId)?.name??'Объект недоступен':f.valueKind==='date'?`${f.datePrecision==='circa'?'Около ':''}${f.dateStart}${f.dateStart!==f.dateEnd?' — '+f.dateEnd:''}`:f.valueKind==='boolean'?(f.valueBoolean?'Да':'Нет'):String(f.valueText??f.valueNumber??'');
