import {z} from 'zod';
const name=z.string().trim().min(1).max(200);
const source=z.object({kind:z.enum(['url','pack','manual']).optional(),url:z.string().url().refine(s=>s.startsWith('https://')).optional(),name,locator:z.string().optional(),family:z.string().optional()}).strict().refine(s=>s.kind==='manual'||!!s.url,'Укажите HTTPS-источник или kind: manual');
const verification=z.enum(['user_confirmed','direct','verified','unverified','ambiguous','conflict','rejected']);
export type Reference={name:string;type:string;aliases?:string[];externalIds?:Record<string,string>;qualifiers?:Record<string,unknown>};
export const referenceSchema:z.ZodType<Reference>=z.object({name,type:name,aliases:z.array(name).optional(),externalIds:z.record(z.string()).optional(),qualifiers:z.record(z.unknown()).optional()}).strict();
const fact=z.object({property:name,value:z.unknown().refine(v=>v!==undefined,'Нет значения'),source:source.optional(),sources:z.array(source).optional(),verification:verification.default('unverified'),learnable:z.boolean().optional()}).strict();
const image=z.object({file:z.string().regex(/^media\/[A-Za-z0-9._/-]+$/),role:name.default('primary'),sourceUrl:z.string().url().refine(s=>s.startsWith('https://')).optional(),license:name,primary:z.boolean().optional(),recognition:z.boolean().optional()}).strict();
const property=z.object({name,aliases:z.array(name).default([]),valueType:z.enum(['entity','text','number','date','boolean']),multiple:z.boolean().default(false),learnable:z.boolean().default(true),subjectTypes:z.array(name).optional(),targetTypes:z.array(name).optional(),promptTemplates:z.object({forward:name.optional(),reverse:name.optional(),timeline:name.optional(),sort:z.string().max(1000).optional()}).strict().optional(),inverse:z.object({enabled:z.boolean(),name:name.optional()}).strict().optional(),learning:z.object({forward:z.boolean().optional(),reverse:z.boolean().optional(),choice:z.enum(['auto','on','off']).optional(),recallReveal:z.enum(['auto','on','off']).optional(),match:z.enum(['auto','on','off']).optional(),categorize:z.enum(['auto','on','off']).optional(),timeline:z.enum(['auto','on','off']).optional(),sort:z.enum(['auto','on','off']).optional(),missing:z.enum(['auto','on','off']).optional()}).strict().optional()}).strict();
// Use one strict object: an intersection with a strict reference would reject entity fields.
const entitySchema=z.object({name,type:name,aliases:z.array(name).default([]),externalIds:z.record(z.string()).default({}),qualifiers:z.record(z.unknown()).optional(),description:z.string().max(400).optional(),completeProperties:z.array(name).default([]),facts:z.array(fact).default([]),properties:z.record(z.unknown()).optional(),tags:z.array(name).default([]),images:z.array(image).default([])}).strict();
export const schemaV3=z.object({schemaVersion:z.literal(3),name,description:z.string().max(1000).optional(),properties:z.array(property).max(5000).default([]),entityTypes:z.array(z.object({name,aliases:z.array(name).default([])}).strict()).default([]),entities:z.array(entitySchema).max(50000),deck:z.object({name,description:z.string().optional(),members:z.array(referenceSchema),learning:z.object({properties:z.array(name).optional(),imageRecognition:z.boolean().default(true)}).strict().default({imageRecognition:true})}).strict().optional()}).strict();
export type PackageV3=z.infer<typeof schemaV3>;
export const normalizeName=(s:string)=>s.normalize('NFKC').trim().replace(/\s+/g,' ').toLowerCase().replace(/ё/g,'е');
export function parseV3(raw:unknown):PackageV3{
 const walk=(v:unknown)=>{if(Array.isArray(v))v.forEach(walk);else if(v&&typeof v==='object')for(const [key,value] of Object.entries(v)){if(['id','entityId','factId','valueEntityId','tagId','mediaId','deckId','packId'].includes(key))throw Error(`В пакете v3 запрещён технический ключ ${key}`);walk(value)}};walk(raw);
 return schemaV3.parse(raw);
}
