import type {Bundle,Entity,Fact,Source,PropertyDefinition,Deck} from '../types';
import {properties,entityTypes,factValue,textValue} from '../knowledge/properties';
import {validDate,validateImport} from '../validate';
import {normalizeName as norm,referenceSchema,type Reference,type PackageV3} from './schema-v3';
export type ImportIssue={key:string;kind:'entity'|'fact'|'deck';label:string;detail:string;options:{value:string;label:string}[]};
export type ImportDecisions=Record<string,string>;
export type ImportPlan={bundle:Bundle;issues:ImportIssue[];resetFactIds:string[];entityIds:string[];factIds:string[];stats:{newEntities:number;matchedEntities:number;newFacts:number;existingFacts:number};deckId?:string};
const names=(r:{name:string;aliases?:string[]})=>new Set([r.name,...r.aliases??[]].map(norm));
const intersects=(a:Set<string>,b:Set<string>)=>[...a].some(x=>b.has(x));
const uniqueSources=(s:Source[])=>[...new Map(s.map(x=>[JSON.stringify([x.url,x.name,x.locator,x.family]),x])).values()];
export function dateValue(v:unknown):Pick<Fact,'dateStart'|'dateEnd'|'datePrecision'>{
 if(v&&typeof v==='object'){
  const o=v as Record<string,unknown>;
  if('start'in o){const a=dateValue(o.start),b=dateValue(o.end??o.start);return {dateStart:a.dateStart,dateEnd:b.dateEnd,datePrecision:o.approximate?'circa':'range'}}
  if('value'in o){const a=dateValue(o.value);return {...a,datePrecision:o.approximate?'circa':a.datePrecision}}
 }
 let s=String(v).trim(),approx=/^(?:circa|c\.|около)\s*/i.test(s);s=s.replace(/^(?:circa|c\.|около)\s*/i,'');
 if(/^\d{4}$/.test(s))return {dateStart:s+'-01-01',dateEnd:s+'-12-31',datePrecision:approx?'circa':'year'};
 if(/^\d{4}-\d{2}$/.test(s)){const [y,m]=s.split('-').map(Number);if(m<1||m>12)throw Error('Неверный месяц');const end=new Date(Date.UTC(y,m,0)).toISOString().slice(0,10);return {dateStart:s+'-01',dateEnd:end,datePrecision:approx?'circa':'month'}}
 if(validDate(s))return {dateStart:s,dateEnd:s,datePrecision:approx?'circa':'day'};
 throw Error(`Неверная дата: ${String(v)}`);
}
const valueKey=(f:Fact)=>f.valueKind==='text'?JSON.stringify(['text',norm(f.valueText??'')]):factValue(f);
const isTrusted=(f:Fact)=>!f.archived&&['verified','direct','user_confirmed'].includes(f.verification);
export function buildImportPlan(pkg:PackageV3,current:Bundle,decisions:ImportDecisions={},seed:string=crypto.randomUUID(),mediaUrls:Record<string,string>={}):ImportPlan{
 const b:Bundle=structuredClone({...current,properties:properties(current),entityTypes:entityTypes(current),decks:current.decks??[],deckMembers:current.deckMembers??[]});
 const issues:ImportIssue[]=[],reset=new Set<string>(),matched=new Set<string>(),newEntities=new Set<string>();let serial=0,existingFacts=0,newFacts=0;const touchedFacts=new Set<string>();
 const id=(kind:string,path?:string)=>`local.${seed}.${kind}.${path??++serial}`;
 const type=(name:string):string=>{const candidate=b.entityTypes!.filter(t=>intersects(names(t),new Set([norm(name)]))||norm(t.id)===norm(name));if(candidate.length>1)throw Error(`Неоднозначный тип ${name}`);if(candidate.length)return candidate[0].id;const aliases:Record<string,string>={person:'Человек',artwork:'Картина',book:'Книга',film:'Фильм',country:'Страна',city:'Город',event:'Событие',organization:'Организация',concept:'Понятие'};if(aliases[norm(name)])return type(aliases[norm(name)]);const t={id:id('type'),name,origin:'pack' as const};b.entityTypes!.push(t);return t.id};
 for(const t of pkg.entityTypes){const key=type(t.name),row=b.entityTypes!.find(x=>x.id===key)!;row.aliases=[...new Set([...row.aliases??[],...t.aliases])];}
 const property=(name:string)=>{const list=b.properties!.filter(p=>!p.archived&&(intersects(names(p),new Set([norm(name)]))||norm(p.id)===norm(name)));if(list.length!==1)throw Error(list.length?`Неоднозначное свойство ${name}`:`Опишите свойство «${name}» в properties`);return list[0]};
 for(const p of pkg.properties){const list=b.properties!.filter(x=>!x.archived&&intersects(names(x),names(p)));if(list.length>1)throw Error(`Неоднозначное свойство ${p.name}`);const old=list[0];if(old&&(old.valueKind!==p.valueType||old.cardinality!==(p.multiple?'many':'one')))throw Error(`Несовместимое определение поля «${p.name}»: тип или множественность отличаются. Исправьте пакет или существующее поле.`);
 if(old){old.aliases=[...new Set([...old.aliases??[],...p.aliases])];continue}
 const next:PropertyDefinition={id:id('property'),name:p.name,aliases:p.aliases,valueKind:p.valueType,cardinality:p.multiple?'many':'one',learnable:p.learnable,subjectTypes:p.subjectTypes?.map(type),targetTypes:p.targetTypes?.map(type),promptTemplates:p.promptTemplates,inverse:p.inverse,learning:p.learning,origin:'pack'};b.properties!.push(next);}
 const declared=new Map<string,Entity>();
 const scalar=(f:Fact,v:unknown)=>{if(f.valueKind==='entity'){const r=referenceSchema.safeParse(v);const target=b.entities.find(e=>e.id===f.valueEntityId);return r.success&&!!target&&target.type===type(r.data.type)&&intersects(names(target),names(r.data))}if(f.valueKind==='date'){const d=dateValue(v);return f.dateStart!<=d.dateEnd!&&d.dateStart!<=f.dateEnd!}if(f.valueKind==='number'){const o=v&&typeof v==='object'?v as {value?:unknown;unit?:string}:undefined;return f.valueNumber===Number(o?.value??v)&&(f.unit??'')===(o?.unit??'')}if(f.valueKind==='boolean')return f.valueBoolean===v;return norm(f.valueText??'')===norm(String(v))};
 // Identity evidence is checked before changing facts, including declarations later in this package.
 const identityById=new Map<string,Record<string,unknown>>();
 const matchesEvidence=(e:Entity,ref:Reference,evidence:Record<string,unknown>)=>{let contradiction=false,confirmed=0;for(const [key,v]of Object.entries(evidence)){const p=property(key),fs=b.facts.filter(f=>f.entityId===e.id&&f.key===p.id&&!['rejected','conflict','ambiguous'].includes(f.verification)),staged=identityById.get(e.id)?.[p.id];if(staged!==undefined){const ra=referenceSchema.safeParse(staged),rb=referenceSchema.safeParse(v);const same=ra.success&&rb.success?type(ra.data.type)===type(rb.data.type)&&intersects(names(ra.data),names(rb.data)):p.valueKind==='date'?(()=>{const a=dateValue(staged),c=dateValue(v);return a.dateStart!<=c.dateEnd!&&c.dateStart!<=a.dateEnd!})():typeof staged==='string'&&typeof v==='string'?norm(staged)===norm(v):JSON.stringify(staged)===JSON.stringify(v);if(same)confirmed++;else contradiction=true;continue}if(fs.length){if(fs.some(f=>scalar(f,v)))confirmed++;else if(p.cardinality==='one'||['Автор','Изобретатель'].includes(p.name)||key in(ref.qualifiers??{}))contradiction=true}}
 for(const [key,v]of Object.entries(ref.externalIds??{})){if(e.externalIds[key]&&e.externalIds[key]!==v)contradiction=true;else if(e.externalIds[key]===v)confirmed++}return {contradiction,confirmed}};
 const resolve=(ref:Reference,path:string,evidence:Record<string,unknown>={}):Entity=>{
  const t=type(ref.type),n=names(ref);let candidates=b.entities.filter(e=>!e.mergedInto&&e.type===t&&(intersects(names(e),n)||Object.entries(ref.externalIds??{}).some(([k,v])=>e.externalIds[k]===v)));
  const compatible=candidates.filter(e=>!matchesEvidence(e,ref,evidence).contradiction),confirmed=compatible.filter(e=>matchesEvidence(e,ref,evidence).confirmed>0);if(confirmed.length===1)candidates=confirmed;else if(compatible.length===1&&candidates.length===1)candidates=compatible;
  const key='entity:'+path,choice=decisions[key];let e:Entity|undefined;
  if(choice&&choice!=='new'){e=candidates.find(x=>x.id===choice);if(!e)throw Error('Решение сопоставления устарело')}
  else if(choice!=='new'&&candidates.length===1&&!candidates[0].archived&&!matchesEvidence(candidates[0],ref,evidence).contradiction)e=candidates[0];
  else if(!choice&&candidates.length){issues.push({key,kind:'entity',label:ref.name,detail:'Совпадающее имя требует выбора: есть несколько объектов, архивная запись или противоречащие сведения. В пакете: '+Object.entries(evidence).map(([key,value])=>key+': '+(value&&typeof value==='object'&&'name'in value?(value as {name:string}).name:JSON.stringify(value))).join('; '),options:[...candidates.map(x=>({value:x.id,label:`${x.name}${x.archived?' (архив)':''} · ${x.summary??''} ${b.facts.filter(f=>f.entityId===x.id&&!f.archived).slice(0,3).map(f=>`${b.properties!.find(p=>p.id===f.key)?.name}: ${textValue(f,b)}`).join('; ')}`})),{value:'new',label:'Создать отдельный объект'}]});}
  if(!e){e={id:id('entity',path),name:ref.name,type:t,aliases:ref.aliases??[],externalIds:ref.externalIds??{},origin:'pack'};b.entities.push(e);newEntities.add(e.id)}else {matched.add(e.id);e.aliases=[...new Set([...e.aliases,...ref.aliases??[],...norm(e.name)!==norm(ref.name)?[ref.name]:[]])];e.externalIds={...e.externalIds,...ref.externalIds};if(choice)e.archived=false}
  const identity={...identityById.get(e.id)};for(const [k,v]of Object.entries(evidence))identity[property(k).id]=v;identityById.set(e.id,identity);return e;
 };
 const allFacts=(e:PackageV3['entities'][number])=>[...e.facts,...Object.entries(e.properties??{}).map(([property,value])=>({property,value,verification:'unverified' as const})),...Object.entries(e.qualifiers??{}).filter(([k])=>!e.facts.some(f=>f.property===k)&&!(k in(e.properties??{}))).map(([property,value])=>({property,value,verification:'unverified' as const}))];
 const identityEvidence=(e:PackageV3['entities'][number])=>({...Object.fromEntries(allFacts(e).filter(f=>property(f.property).cardinality==='one'||['Автор','Изобретатель'].includes(f.property)).map(f=>[f.property,f.value])),...e.qualifiers});
 pkg.entities.forEach((ref,n)=>{const e=resolve(ref,`declaration.${n}`,identityEvidence(ref));declared.set(String(n),e);if(!e.summary&&ref.description)e.summary=ref.description});
 const pendingReferences:{entity:Entity;ref:Reference}[]=[];
 const resolveRef=(raw:unknown,path:string)=>{const ref=referenceSchema.parse(raw);const t=type(ref.type),candidates=pkg.entities.map((e,n)=>({ref:e,e:declared.get(String(n))!})).filter(x=>x.e.type===t&&intersects(names(x.ref),names(ref))&&Object.entries(ref.qualifiers??{}).every(([k,v])=>!matchesEvidence(x.e,ref,{[k]:v}).contradiction));const unique=[...new Map(candidates.map(x=>[x.e.id,x.e])).values()];if(unique.length===1&&!Object.keys(ref.qualifiers??{}).length)return unique[0];const entity=resolve(ref,path,ref.qualifiers??{});if(newEntities.has(entity.id)&&!pkg.entities.some((_,n)=>declared.get(String(n))?.id===entity.id)&&!pendingReferences.some(x=>x.entity.id===entity.id))pendingReferences.push({entity,ref});return entity};
 const makeFact=(entityId:string,key:string,v:unknown,path:string):Fact=>{const p=property(key),base:Fact={id:id('fact',path),entityId,key:p.id,valueKind:p.valueKind,source:{kind:'manual',name:'Пакет без указанного источника'},verification:'unverified',origin:'pack'};
 switch(p.valueKind){case 'entity':base.valueEntityId=resolveRef(v,path).id;break;case 'date':Object.assign(base,dateValue(v));break;case 'text':if(typeof v!=='string'||!v.trim())throw Error(`Ожидается текст в ${key}`);base.valueText=v.trim();break;case 'boolean':if(typeof v!=='boolean')throw Error(`Ожидается true/false в ${key}`);base.valueBoolean=v;break;case 'number':{const o=v&&typeof v==='object'?v as {value?:unknown;unit?:string}:undefined;const value=o?.value??v;if(typeof value!=='number'||!Number.isFinite(value))throw Error(`Ожидается число в ${key}`);base.valueNumber=value;base.unit=o?.unit;break;}}
 return base;};
 pkg.entities.forEach((ref,n)=>{const e=declared.get(String(n))!;allFacts(ref).forEach((raw,j)=>{const f=makeFact(e.id,raw.property,raw.value,`fact.${n}.${j}`);const supplied=uniqueSources([...(('source'in raw&&raw.source)?[raw.source]:[]),...(('sources'in raw&&raw.sources)?raw.sources:[])]);f.source=supplied[0]??f.source;f.sources=supplied.length?supplied:[f.source];f.completeSet=ref.completeProperties.some(key=>property(key).id===f.key);f.verification=raw.verification;if(!supplied.length&&f.verification!=='unverified')throw Error(`Подтверждённый факт «${raw.property}» требует источника`);if('learnable'in raw)f.learnable=raw.learnable;
 const same=b.facts.find(x=>!x.archived&&x.entityId===f.entityId&&x.key===f.key&&valueKey(x)===valueKey(f));if(same){touchedFacts.add(same.id);same.sources=uniqueSources([same.source,...same.sources??[],...f.sources]);if(f.completeSet)same.completeSet=true;if(same.verification==='unverified'&&isTrusted(f))same.verification=f.verification;existingFacts++;return}
 const others=b.facts.filter(x=>!x.archived&&x.entityId===f.entityId&&x.key===f.key&&x.verification!=='rejected');if(property(raw.property).cardinality==='one'&&others.length){const key=`fact:${n}.${j}`,choice=decisions[key];if(!choice)issues.push({key,kind:'fact',label:`${e.name} — ${raw.property}`,detail:`В базе: ${others.map(x=>textValue(x,b)).join(', ')}. В пакете: ${textValue(f,b)}.`,options:[{value:'keep',label:'Оставить существующее'},{value:'replace',label:'Принять новое значение'},{value:'disputed',label:'Сохранить оба как спорные'}]});if(!choice||choice==='keep'){others.forEach(f=>touchedFacts.add(f.id));return;}if(choice==='replace'){for(const old of others){old.archived=true;reset.add(old.id)}}else if(choice==='disputed'){for(const old of others)old.verification='conflict';f.verification='conflict'}else throw Error('Неверное решение конфликта');}
 b.facts.push(f);touchedFacts.add(f.id);newFacts++;});
 for(const tagName of ref.tags){let tag=b.tags.find(t=>!t.archived&&norm(t.name)===norm(tagName));if(!tag){tag={id:id('tag'),name:tagName,origin:'pack'};b.tags.push(tag)}if(!b.entityTags.some(t=>t.entityId===e.id&&t.tagId===tag!.id&&!t.archived))b.entityTags.push({entityId:e.id,tagId:tag.id,origin:'pack'});}
 for(const img of ref.images){const imageUrl=mediaUrls[img.file]??img.file;if(!img.sourceUrl)throw Error(`Изображение ${img.file} требует sourceUrl`);if(b.media.some(m=>!m.archived&&m.entityId===e.id&&m.url===imageUrl&&m.role===img.role))continue;const primary=img.primary===true&&!b.media.some(m=>m.entityId===e.id&&m.primary&&!m.archived);b.media.push({id:id('media'),entityId:e.id,url:imageUrl,role:img.role,license:img.license,sourceUrl:img.sourceUrl,primary,learningExemplar:img.recognition!==false,origin:'pack'});}
 });
 let deckId:string|undefined;
 if(pkg.deck){const spec=pkg.deck,candidates=b.decks!.filter(d=>!d.archived&&norm(d.name)===norm(spec.name)),choice=decisions.deck;let deck:Deck|undefined;
 if(choice&&choice!=='new'){deck=b.decks!.find(d=>d.id===choice&&!d.archived);if(!deck)throw Error('Колода для обновления не найдена')}
 if(!choice&&candidates.length)issues.push({key:'deck',kind:'deck',label:spec.name,detail:'Колода с этим названием уже есть. Выберите, куда добавить знания.',options:[...candidates.map(d=>({value:d.id,label:`Добавить в «${d.name}» (${b.deckMembers!.filter(m=>m.deckId===d.id&&!m.archived).length} объектов)`})),{value:'new',label:'Создать отдельную колоду'}]});
 const propertyIds=spec.learning.properties?.map(k=>property(k).id);
 if(!deck){deck={id:id('deck'),name:spec.name,description:spec.description,learning:{propertyIds,imageRecognition:spec.learning.imageRecognition},origin:'pack'};b.decks!.push(deck)} // Existing settings are user choices; imports only add members.
 deckId=deck.id;for(const [n,ref]of spec.members.entries()){const e=resolveRef(ref,`member.${n}`);const old=b.deckMembers!.find(m=>m.deckId===deck!.id&&m.entityId===e.id);if(!old)b.deckMembers!.push({deckId:deck.id,entityId:e.id,origin:'pack'});else if(!old.userModified)old.archived=false;}
 }
 for(let n=0;n<pendingReferences.length;n++){const {entity,ref}=pendingReferences[n];for(const [key,value]of Object.entries(ref.qualifiers??{})){const f=makeFact(entity.id,key,value,`reference.${n}.${Object.keys(ref.qualifiers??{}).indexOf(key)}`);if(!b.facts.some(x=>!x.archived&&x.entityId===entity.id&&x.key===f.key&&valueKey(x)===valueKey(f)))b.facts.push(f);}}
 const valid=validateImport(b,current,true);return {bundle:valid,issues,resetFactIds:[...reset],entityIds:[...new Set([...matched,...newEntities])],factIds:[...touchedFacts],stats:{newEntities:newEntities.size,matchedEntities:matched.size,newFacts,existingFacts},deckId};
}
