import {useEffect,useState} from 'react';
import {db,type PackRow} from '../db/engi-db';
import {storageHealth,protectStorage} from '../services/storage-health';
import {saveBackup} from '../services/backup-service';
import {toast} from 'sonner';
import {useStudyPreferences} from './study/useStudyPreferences';
export function SettingsPanel({revision,onImport,onRestore}:{revision:number;onImport:()=>void;onRestore:()=>void}){
 const {preferences,save}=useStudyPreferences();
 const [health,setHealth]=useState<Awaited<ReturnType<typeof storageHealth>>>();const [packs,setPacks]=useState<PackRow[]>([]);
 async function refresh(){try{setHealth(await storageHealth());setPacks(await db.installedPacks.toArray())}catch(e){toast.error((e as Error).message)}}
 useEffect(()=>{refresh()},[revision]);const mb=(n:number)=>`${Math.round(n/1024/1024)} МБ`;
 return <><section className="panel study-preferences"><h2>Практика</h2><label className="check-label"><input type="checkbox" checked={preferences.sound} onChange={async e=>{try{await save({...preferences,sound:e.target.checked})}catch(error){toast.error((error as Error).message)}}}/>Тихий звук верного ответа</label><label className="check-label"><input type="checkbox" checked={preferences.accessibleRecall} onChange={async e=>{try{await save({...preferences,accessibleRecall:e.target.checked})}catch(error){toast.error((error as Error).message)}}}/>Компактные кнопки вместо свайпа для воспоминания</label><small>Ответ открывается через 5 секунд. Оценка доступна после раскрытия. Звук по умолчанию выключен.</small></section><section className="panel"><div className="section-heading"><h2>Наборы</h2><button className="button primary" onClick={onImport}>Импортировать пакет</button></div>{packs.length?packs.map(p=><div className="review-row" key={p.packId}><div><h3>{p.name}</h3><p className="muted">v{p.packVersion} · {p.entityIds.length} объектов · {p.factIds.length} фактов · {p.files.length} изображений</p></div></div>):<p className="muted">Пока нет наборов знаний. Выберите файл .engi из папки на ПК или приложения «Файлы».</p>}</section><section className="panel storage-panel"><h2>Хранилище</h2>{health&&<><dl><div><dt>Локальные данные</dt><dd>{health.persisted?'Защищены браузером':'Обычный режим'}</dd></div><div><dt>Использовано</dt><dd>{mb(health.usage)}</dd></div><div><dt>Доступно примерно</dt><dd>{health.quota?mb(Math.max(0,health.quota-health.usage)):'Браузер не сообщил'}</dd></div><div><dt>Пакетов</dt><dd>{health.packs}</dd></div><div><dt>Событий истории</dt><dd>{health.reviews}</dd></div><div><dt>Последняя копия</dt><dd>{health.lastBackupAt?new Date(health.lastBackupAt).toLocaleString('ru-RU'):'Ещё не сохранена'}</dd></div></dl>{health.backupNeeded&&<p className="backup-reminder">Прогресс давно не сохранялся. Сохраните копию в «Файлы» или на другой диск.</p>}<div className="import-buttons"><button className="button primary" onClick={async()=>{try{await saveBackup();await refresh()}catch(e){toast.error((e as Error).message)}}}>Сохранить резервную копию</button><button className="button outline" onClick={onRestore}>Восстановить из копии</button>{!health.persisted&&<button className="button outline" onClick={async()=>{try{const result=await protectStorage();toast.info(result?'Хранилище защищено':'Браузер не предоставил защиту. Используйте резервные копии.');refresh()}catch(e){toast.error((e as Error).message)}}}>Защитить локальные данные</button>}</div><p className="muted">Данные находятся на этом устройстве. Резервная копия сохраняет прогресс, настройки, личные знания, правки и свои изображения. Изображения из пакетов восстановите повторным импортом .engi. Очистка данных сайта удаляет локальное хранилище даже при включённой защите.</p></>}</section></>
}
