import {SettingsIcon} from './ui/AppIcons';
import type {PreparedImport} from './services/declarative-pack';
import type {ImportDecisions} from './lib/engi/import/semantic-merge';

import {lazy,Suspense,useEffect,useMemo,useRef,useState} from 'react';
import {Toaster,toast} from 'sonner';
import type {Snapshot} from './lib/engi/types';
import type {SessionRow} from './db/engi-db';
import {trainerService} from './services/trainer-service';

import {db} from './db/engi-db';
import {DecksHome} from './components/collections/DecksHome';
import {cleanDeckSelection,createDeckTargetIndex,DECK_SELECTION_KEY,type DeckSelection} from './services/deck-overview';
import {readLifecycle} from './services/learning-lifecycle-service';
import type {LearningLifecycle} from './lib/engi/study-core/acquisition';

import {registerUpdates,applyUpdate,checkUpdates} from './pwa/update-manager';
import {protectStorage} from './services/storage-health';
import {feedSpan,measureFeed} from './services/feed-performance';
const ImportPreview=lazy(()=>import('./components/knowledge/ImportPreview').then(module=>({default:module.ImportPreview})));
const ProgressDashboard=lazy(()=>import('./components/progress/ProgressDashboard').then(module=>({default:module.ProgressDashboard})));
const SettingsPanel=lazy(()=>import('./components/settings-panel').then(module=>({default:module.SettingsPanel})));
let LoadedStudyFeed:typeof import('./components/study/StudyFeed')['StudyFeed']|undefined;
const loadStudyFeed=()=>measureFeed('ui.module',()=>import('./components/study/StudyFeed')).then(module=>{LoadedStudyFeed=module.StudyFeed;return module;});
const StudyFeed=lazy(()=>loadStudyFeed().then(module=>({default:module.StudyFeed})));
export default function App(){
 const [selection,setSelection]=useState<DeckSelection>({ids:[],lastStudied:{}}),[lifecycle,setLifecycle]=useState<LearningLifecycle>();const selectionWrites=useRef(Promise.resolve());
 const [prepared,setPrepared]=useState<PreparedImport|null>(null);
 const [s,setS]=useState<Snapshot|null>(null),[error,setError]=useState(''),[tab,setTab]=useState('today'),[feed,setFeed]=useState<SessionRow|null>(null),[resume,setResume]=useState<SessionRow|undefined>(),[busy,setBusy]=useState(false),[importOpen,setImportOpen]=useState(false),[importProgress,setImportProgress]=useState(''),[update,setUpdate]=useState(false),[revision,setRevision]=useState(0);const file=useRef<HTMLInputElement>(null),abort=useRef<AbortController|null>(null);
 const targetIndex=useMemo(()=>s?createDeckTargetIndex(s.bundle):undefined,[s?.bundle]);
 // Keep the first paint small, then fetch the game UI while the user chooses decks.
 useEffect(()=>{if(!s)return;const warm=()=>{void loadStudyFeed().catch(()=>{});};if('requestIdleCallback' in window){const id=window.requestIdleCallback(warm,{timeout:1000});return()=>window.cancelIdleCallback(id);}const id=setTimeout(warm,200);return()=>clearTimeout(id);},[!!s]);
 async function reload(){try{const snapshot=await trainerService.getGoalSnapshot(true);const stored=await db.appMeta.get(DECK_SELECTION_KEY);setSelection(cleanDeckSelection(stored?.value,snapshot));setLifecycle(await readLifecycle(db));setS(snapshot);const active=snapshot.bundle.decks?.some(d=>!d.archived)?undefined:await trainerService.getResumableSession({endless:true});setResume(active?.memoryModel==='goals'&&active.feed&&(active.intro||active.exhausted||active.tasks[active.currentPosition])?active:undefined);setRevision(n=>n+1);setError('')}catch(e){setError((e as Error).message)}}
 useEffect(()=>{reload();return registerUpdates(()=>setUpdate(true),()=>{})},[]);
 async function readFile(f:File){setBusy(true);abort.current=new AbortController();try{const name=f.name.toLowerCase();if(name.endsWith('.engi')){const {prepareDeclarativePack}=await import('./services/declarative-pack');const next=await prepareDeclarativePack(f,undefined,setImportProgress,abort.current.signal);if(next){setPrepared(next);setImportOpen(true);return}await (await import('./services/pack-service')).importPack(f,setImportProgress,undefined,abort.current.signal);toast.success('Пакет импортирован');await protectStorage()}else if(name.endsWith('.engi-backup')){if(f.size>700*1024*1024)throw Error('Копия больше 700 МБ');await (await import('./services/backup-service')).restoreBackup(JSON.parse(await f.text()));toast.success('Прогресс и личные знания восстановлены')}else throw Error('Выберите .engi или .engi-backup');await reload();setImportOpen(false)}catch(e){if((e as Error).name!=='AbortError')toast.error((e as Error).message)}finally{setBusy(false);setImportProgress('');abort.current=null}}
 async function commitImport(decisions:ImportDecisions){if(!prepared)return;setBusy(true);abort.current=new AbortController();try{await (await import('./services/declarative-pack')).commitDeclarativeImport(prepared,decisions,undefined,setImportProgress,abort.current.signal);setPrepared(null);setImportOpen(false);toast.success('Пакет импортирован');await protectStorage();await reload()}catch(e){if((e as Error).name!=='AbortError')toast.error((e as Error).message)}finally{setBusy(false);setImportProgress('');abort.current=null}}
 const FeedComponent=LoadedStudyFeed??StudyFeed;
 if(feed)return <><Toaster richColors/><Suspense fallback={<div className="app-shell"><main className="workspace">Открываем задание…</main></div>}><FeedComponent initial={feed} onExit={()=>{setFeed(null);reload()}}/></Suspense></>;
 function toggleDeck(id:string){const next={...selection,ids:selection.ids.includes(id)?selection.ids.filter(x=>x!==id):[...selection.ids,id]};setSelection(next);selectionWrites.current=selectionWrites.current.catch(()=>{}).then(async()=>{await db.appMeta.put({key:DECK_SELECTION_KEY,value:next})});void selectionWrites.current.catch(e=>toast.error(e.message));}
 async function startSelected(){const end=feedSpan('ui.start');void loadStudyFeed().catch(()=>{});setBusy(true);try{await selectionWrites.current;const ids=[...selection.ids],active=await trainerService.getResumableSession({endless:true}),same=active?.deckIds&&JSON.stringify([...active.deckIds].sort())===JSON.stringify([...ids].sort());const next=same?active!:await trainerService.startGoalFeed('all','mixed','daily',{endless:true,deckIds:ids});const lastStudied={...selection.lastStudied};for(const id of ids)lastStudied[id]=new Date().toISOString();await db.appMeta.put({key:DECK_SELECTION_KEY,value:{ids,lastStudied}});await loadStudyFeed();setFeed(next);}catch(e){toast.error((e as Error).message)}finally{end();setBusy(false)}}
 return <><Toaster richColors/><div className="app-shell deck-app"><header className="header"><nav className="main-tabs" aria-label="Основные разделы"><button className={`main-tab ${tab==='today'?'is-active':''}`} aria-current={tab==='today'?'page':undefined} onClick={()=>{setTab('today')}}>Колоды</button><button className={`main-tab ${tab==='progress'?'is-active':''}`} aria-current={tab==='progress'?'page':undefined} onClick={()=>setTab('progress')}>Статистика</button></nav><button className={`settings-link ${tab==='storage'?'is-active':''}`} aria-label="Настройки" aria-pressed={tab==='storage'} onClick={()=>setTab('storage')}><SettingsIcon/></button></header>{update&&<div className="notice">Доступно обновление <button className="button outline" onClick={()=>applyUpdate()}>Обновить</button></div>}{error&&<div className="notice" role="alert">{error}<button onClick={reload}>Повторить загрузку</button></div>}<main className="workspace"><Suspense fallback={<p>Открываем…</p>}>{!s?<p>Загрузка…</p>:tab==='progress'?<ProgressDashboard snapshot={s} targetIndex={targetIndex!} onReload={reload} onStudy={()=>void startSelected()}/>:tab==='storage'?<><div className="page-heading"><h1>Настройки</h1></div><SettingsPanel revision={revision} onPreferencesSaved={reload} onImport={()=>setImportOpen(true)} onRestore={()=>file.current?.click()}/><section className="panel"><button className="button outline" onClick={async()=>{try{await checkUpdates();toast.info('Проверка обновлений выполнена')}catch(e){toast.error((e as Error).message)}}}>Проверить обновление</button></section></>:<DecksHome snapshot={s} lifecycle={lifecycle} selection={selection} targetIndex={targetIndex!} busy={busy} onToggle={toggleDeck} onStart={()=>void startSelected()} onImport={()=>setImportOpen(true)} legacyResume={!s.bundle.decks?.some(d=>!d.archived)&&resume?.deckIds===undefined&&!!resume?()=>setFeed(resume):undefined}/>}</Suspense></main></div><input ref={file} type="file" hidden onChange={e=>{const f=e.target.files?.[0];if(f)readFile(f);e.target.value=''}}/>{importOpen&&<div className="overlay"><section className="editor-panel"><div className="section-heading"><h2>Импортировать пакет</h2><button className="icon-button" disabled={busy} onClick={()=>{setImportOpen(false);setPrepared(null)}}>×</button></div>{prepared?<Suspense fallback={<p>Открываем импорт…</p>}><ImportPreview prepared={prepared} busy={busy} onCommit={commitImport} onCancel={()=>{setPrepared(null);setImportOpen(false)}}/></Suspense>:<><p>Выберите .engi из приложения «Файлы» или папки на компьютере.</p><button className="button primary" disabled={busy} onClick={()=>file.current?.click()}>Выбрать файл</button></>}{busy&&<><p role="status">{importProgress||'Проверяем копию…'}</p><button className="button outline" onClick={()=>abort.current?.abort()}>Отменить импорт</button></>}<p className="muted">.engi-backup сохраняет знания, колоды, прогресс и изображения.</p></section></div>}</>;
}




